// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// AppsAPIRestV0OrganizationListOrganizationOrdering - Ordering field
type AppsAPIRestV0OrganizationListOrganizationOrdering string

const (
	AppsAPIRestV0OrganizationListOrganizationOrderingCreatedAt      AppsAPIRestV0OrganizationListOrganizationOrdering = "created_at"
	AppsAPIRestV0OrganizationListOrganizationOrderingMinusCreatedAt AppsAPIRestV0OrganizationListOrganizationOrdering = "-created_at"
	AppsAPIRestV0OrganizationListOrganizationOrderingUpdatedAt      AppsAPIRestV0OrganizationListOrganizationOrdering = "updated_at"
	AppsAPIRestV0OrganizationListOrganizationOrderingMinusUpdatedAt AppsAPIRestV0OrganizationListOrganizationOrdering = "-updated_at"
)

func (e AppsAPIRestV0OrganizationListOrganizationOrdering) ToPointer() *AppsAPIRestV0OrganizationListOrganizationOrdering {
	return &e
}
func (e *AppsAPIRestV0OrganizationListOrganizationOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = AppsAPIRestV0OrganizationListOrganizationOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AppsAPIRestV0OrganizationListOrganizationOrdering: %v", v)
	}
}

type AppsAPIRestV0OrganizationListOrganizationRequest struct {
	// Location of the organization
	Location *string `queryParam:"style=form,explode=true,name=location"`
	// Ordering field
	Ordering *AppsAPIRestV0OrganizationListOrganizationOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                                             `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                                             `queryParam:"style=form,explode=true,name=page_size"`
}

func (a AppsAPIRestV0OrganizationListOrganizationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppsAPIRestV0OrganizationListOrganizationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *AppsAPIRestV0OrganizationListOrganizationRequest) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *AppsAPIRestV0OrganizationListOrganizationRequest) GetOrdering() *AppsAPIRestV0OrganizationListOrganizationOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *AppsAPIRestV0OrganizationListOrganizationRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AppsAPIRestV0OrganizationListOrganizationRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type AppsAPIRestV0OrganizationListOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedOrganizationSchema *components.PagedOrganizationSchema
}

func (o *AppsAPIRestV0OrganizationListOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0OrganizationListOrganizationResponse) GetPagedOrganizationSchema() *components.PagedOrganizationSchema {
	if o == nil {
		return nil
	}
	return o.PagedOrganizationSchema
}
