// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// AppsAPIRestV0EventListEventsOrdering - Ordering field
type AppsAPIRestV0EventListEventsOrdering string

const (
	AppsAPIRestV0EventListEventsOrderingStartDate      AppsAPIRestV0EventListEventsOrdering = "start_date"
	AppsAPIRestV0EventListEventsOrderingMinusStartDate AppsAPIRestV0EventListEventsOrdering = "-start_date"
	AppsAPIRestV0EventListEventsOrderingEndDate        AppsAPIRestV0EventListEventsOrdering = "end_date"
	AppsAPIRestV0EventListEventsOrderingMinusEndDate   AppsAPIRestV0EventListEventsOrdering = "-end_date"
)

func (e AppsAPIRestV0EventListEventsOrdering) ToPointer() *AppsAPIRestV0EventListEventsOrdering {
	return &e
}
func (e *AppsAPIRestV0EventListEventsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start_date":
		fallthrough
	case "-start_date":
		fallthrough
	case "end_date":
		fallthrough
	case "-end_date":
		*e = AppsAPIRestV0EventListEventsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AppsAPIRestV0EventListEventsOrdering: %v", v)
	}
}

type AppsAPIRestV0EventListEventsRequest struct {
	// Ordering field
	Ordering *AppsAPIRestV0EventListEventsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                                `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                                `queryParam:"style=form,explode=true,name=page_size"`
}

func (a AppsAPIRestV0EventListEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppsAPIRestV0EventListEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *AppsAPIRestV0EventListEventsRequest) GetOrdering() *AppsAPIRestV0EventListEventsOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *AppsAPIRestV0EventListEventsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AppsAPIRestV0EventListEventsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type AppsAPIRestV0EventListEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedEventSchema *components.PagedEventSchema
}

func (o *AppsAPIRestV0EventListEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0EventListEventsResponse) GetPagedEventSchema() *components.PagedEventSchema {
	if o == nil {
		return nil
	}
	return o.PagedEventSchema
}
