// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type AppsAPIRestV0MemberGetMemberRequest struct {
	MemberID string `pathParam:"style=simple,explode=false,name=member_id"`
}

func (o *AppsAPIRestV0MemberGetMemberRequest) GetMemberID() string {
	if o == nil {
		return ""
	}
	return o.MemberID
}

type AppsAPIRestV0MemberGetMemberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MemberSchema *components.MemberSchema
}

func (o *AppsAPIRestV0MemberGetMemberResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0MemberGetMemberResponse) GetMemberSchema() *components.MemberSchema {
	if o == nil {
		return nil
	}
	return o.MemberSchema
}
