// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type AppsAPIRestV0OrganizationGetOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
}

func (o *AppsAPIRestV0OrganizationGetOrganizationRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

type AppsAPIRestV0OrganizationGetOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	OrganizationSchema *components.OrganizationSchema
}

func (o *AppsAPIRestV0OrganizationGetOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0OrganizationGetOrganizationResponse) GetOrganizationSchema() *components.OrganizationSchema {
	if o == nil {
		return nil
	}
	return o.OrganizationSchema
}
