// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// AppsAPIRestV0ProjectListProjectsOrdering - Ordering field
type AppsAPIRestV0ProjectListProjectsOrdering string

const (
	AppsAPIRestV0ProjectListProjectsOrderingCreatedAt      AppsAPIRestV0ProjectListProjectsOrdering = "created_at"
	AppsAPIRestV0ProjectListProjectsOrderingMinusCreatedAt AppsAPIRestV0ProjectListProjectsOrdering = "-created_at"
	AppsAPIRestV0ProjectListProjectsOrderingUpdatedAt      AppsAPIRestV0ProjectListProjectsOrdering = "updated_at"
	AppsAPIRestV0ProjectListProjectsOrderingMinusUpdatedAt AppsAPIRestV0ProjectListProjectsOrdering = "-updated_at"
)

func (e AppsAPIRestV0ProjectListProjectsOrdering) ToPointer() *AppsAPIRestV0ProjectListProjectsOrdering {
	return &e
}
func (e *AppsAPIRestV0ProjectListProjectsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = AppsAPIRestV0ProjectListProjectsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AppsAPIRestV0ProjectListProjectsOrdering: %v", v)
	}
}

type AppsAPIRestV0ProjectListProjectsRequest struct {
	// Level of the project
	Level *components.ProjectLevel `queryParam:"style=form,explode=true,name=level"`
	// Ordering field
	Ordering *AppsAPIRestV0ProjectListProjectsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                                    `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                                    `queryParam:"style=form,explode=true,name=page_size"`
}

func (a AppsAPIRestV0ProjectListProjectsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppsAPIRestV0ProjectListProjectsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *AppsAPIRestV0ProjectListProjectsRequest) GetLevel() *components.ProjectLevel {
	if o == nil {
		return nil
	}
	return o.Level
}

func (o *AppsAPIRestV0ProjectListProjectsRequest) GetOrdering() *AppsAPIRestV0ProjectListProjectsOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *AppsAPIRestV0ProjectListProjectsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AppsAPIRestV0ProjectListProjectsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type AppsAPIRestV0ProjectListProjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedProjectSchema *components.PagedProjectSchema
}

func (o *AppsAPIRestV0ProjectListProjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0ProjectListProjectsResponse) GetPagedProjectSchema() *components.PagedProjectSchema {
	if o == nil {
		return nil
	}
	return o.PagedProjectSchema
}
