// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type AppsAPIRestV0ProjectGetProjectRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

func (o *AppsAPIRestV0ProjectGetProjectRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type AppsAPIRestV0ProjectGetProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ProjectSchema *components.ProjectSchema
}

func (o *AppsAPIRestV0ProjectGetProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0ProjectGetProjectResponse) GetProjectSchema() *components.ProjectSchema {
	if o == nil {
		return nil
	}
	return o.ProjectSchema
}
