// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// AppsAPIRestV0ChapterListChaptersOrdering - Ordering field
type AppsAPIRestV0ChapterListChaptersOrdering string

const (
	AppsAPIRestV0ChapterListChaptersOrderingCreatedAt      AppsAPIRestV0ChapterListChaptersOrdering = "created_at"
	AppsAPIRestV0ChapterListChaptersOrderingMinusCreatedAt AppsAPIRestV0ChapterListChaptersOrdering = "-created_at"
	AppsAPIRestV0ChapterListChaptersOrderingUpdatedAt      AppsAPIRestV0ChapterListChaptersOrdering = "updated_at"
	AppsAPIRestV0ChapterListChaptersOrderingMinusUpdatedAt AppsAPIRestV0ChapterListChaptersOrdering = "-updated_at"
)

func (e AppsAPIRestV0ChapterListChaptersOrdering) ToPointer() *AppsAPIRestV0ChapterListChaptersOrdering {
	return &e
}
func (e *AppsAPIRestV0ChapterListChaptersOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = AppsAPIRestV0ChapterListChaptersOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AppsAPIRestV0ChapterListChaptersOrdering: %v", v)
	}
}

type AppsAPIRestV0ChapterListChaptersRequest struct {
	// Country of the chapter
	Country *string `queryParam:"style=form,explode=true,name=country"`
	// Region of the chapter
	Region *string `queryParam:"style=form,explode=true,name=region"`
	// Ordering field
	Ordering *AppsAPIRestV0ChapterListChaptersOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                                    `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                                    `queryParam:"style=form,explode=true,name=page_size"`
}

func (a AppsAPIRestV0ChapterListChaptersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppsAPIRestV0ChapterListChaptersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *AppsAPIRestV0ChapterListChaptersRequest) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *AppsAPIRestV0ChapterListChaptersRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AppsAPIRestV0ChapterListChaptersRequest) GetOrdering() *AppsAPIRestV0ChapterListChaptersOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *AppsAPIRestV0ChapterListChaptersRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *AppsAPIRestV0ChapterListChaptersRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type AppsAPIRestV0ChapterListChaptersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedChapterSchema *components.PagedChapterSchema
}

func (o *AppsAPIRestV0ChapterListChaptersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0ChapterListChaptersResponse) GetPagedChapterSchema() *components.PagedChapterSchema {
	if o == nil {
		return nil
	}
	return o.PagedChapterSchema
}
