// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type AppsAPIRestV0CommitteeGetChapterRequest struct {
	CommitteeID string `pathParam:"style=simple,explode=false,name=committee_id"`
}

func (o *AppsAPIRestV0CommitteeGetChapterRequest) GetCommitteeID() string {
	if o == nil {
		return ""
	}
	return o.CommitteeID
}

type AppsAPIRestV0CommitteeGetChapterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CommitteeSchema *components.CommitteeSchema
}

func (o *AppsAPIRestV0CommitteeGetChapterResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AppsAPIRestV0CommitteeGetChapterResponse) GetCommitteeSchema() *components.CommitteeSchema {
	if o == nil {
		return nil
	}
	return o.CommitteeSchema
}
