// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetChapterRequest struct {
	ChapterID string `pathParam:"style=simple,explode=false,name=chapter_id"`
}

func (g *GetChapterRequest) GetChapterID() string {
	if g == nil {
		return ""
	}
	return g.ChapterID
}

type GetChapterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ChapterSchema *components.ChapterSchema
}

func (g *GetChapterResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetChapterResponse) GetChapterSchema() *components.ChapterSchema {
	if g == nil {
		return nil
	}
	return g.ChapterSchema
}
