// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetCommitteeRequest struct {
	CommitteeID string `pathParam:"style=simple,explode=false,name=committee_id"`
}

func (g *GetCommitteeRequest) GetCommitteeID() string {
	if g == nil {
		return ""
	}
	return g.CommitteeID
}

type GetCommitteeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CommitteeSchema *components.CommitteeSchema
}

func (g *GetCommitteeResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCommitteeResponse) GetCommitteeSchema() *components.CommitteeSchema {
	if g == nil {
		return nil
	}
	return g.CommitteeSchema
}
