// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetChapterRequest struct {
	ChapterID string `pathParam:"style=simple,explode=false,name=chapter_id"`
}

func (o *GetChapterRequest) GetChapterID() string {
	if o == nil {
		return ""
	}
	return o.ChapterID
}

type GetChapterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ChapterSchema *components.ChapterSchema
}

func (o *GetChapterResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetChapterResponse) GetChapterSchema() *components.ChapterSchema {
	if o == nil {
		return nil
	}
	return o.ChapterSchema
}
