// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetEventRequest struct {
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
}

func (g *GetEventRequest) GetEventID() string {
	if g == nil {
		return ""
	}
	return g.EventID
}

type GetEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	EventDetail *components.EventDetail
}

func (g *GetEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEventResponse) GetEventDetail() *components.EventDetail {
	if g == nil {
		return nil
	}
	return g.EventDetail
}
