// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetIssueRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
	RepositoryID   string `pathParam:"style=simple,explode=false,name=repository_id"`
	IssueID        int64  `pathParam:"style=simple,explode=false,name=issue_id"`
}

func (g *GetIssueRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetIssueRequest) GetRepositoryID() string {
	if g == nil {
		return ""
	}
	return g.RepositoryID
}

func (g *GetIssueRequest) GetIssueID() int64 {
	if g == nil {
		return 0
	}
	return g.IssueID
}

type GetIssueResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	IssueDetail *components.IssueDetail
}

func (g *GetIssueResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetIssueResponse) GetIssueDetail() *components.IssueDetail {
	if g == nil {
		return nil
	}
	return g.IssueDetail
}
