// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetMemberRequest struct {
	MemberID string `pathParam:"style=simple,explode=false,name=member_id"`
}

func (g *GetMemberRequest) GetMemberID() string {
	if g == nil {
		return ""
	}
	return g.MemberID
}

type GetMemberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MemberDetail *components.MemberDetail
}

func (g *GetMemberResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMemberResponse) GetMemberDetail() *components.MemberDetail {
	if g == nil {
		return nil
	}
	return g.MemberDetail
}
