// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetMilestoneRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
	RepositoryID   string `pathParam:"style=simple,explode=false,name=repository_id"`
	MilestoneID    int64  `pathParam:"style=simple,explode=false,name=milestone_id"`
}

func (g *GetMilestoneRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetMilestoneRequest) GetRepositoryID() string {
	if g == nil {
		return ""
	}
	return g.RepositoryID
}

func (g *GetMilestoneRequest) GetMilestoneID() int64 {
	if g == nil {
		return 0
	}
	return g.MilestoneID
}

type GetMilestoneResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MilestoneDetail *components.MilestoneDetail
}

func (g *GetMilestoneResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMilestoneResponse) GetMilestoneDetail() *components.MilestoneDetail {
	if g == nil {
		return nil
	}
	return g.MilestoneDetail
}
