// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
}

func (g *GetOrganizationRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

type GetOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	OrganizationDetail *components.OrganizationDetail
}

func (g *GetOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOrganizationResponse) GetOrganizationDetail() *components.OrganizationDetail {
	if g == nil {
		return nil
	}
	return g.OrganizationDetail
}
