// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetProjectRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

func (g *GetProjectRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

type GetProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ProjectSchema *components.ProjectSchema
}

func (g *GetProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectResponse) GetProjectSchema() *components.ProjectSchema {
	if g == nil {
		return nil
	}
	return g.ProjectSchema
}
