// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetRepositoryRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
	RepositoryID   string `pathParam:"style=simple,explode=false,name=repository_id"`
}

func (g *GetRepositoryRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetRepositoryRequest) GetRepositoryID() string {
	if g == nil {
		return ""
	}
	return g.RepositoryID
}

type GetRepositoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RepositoryDetail *components.RepositoryDetail
}

func (g *GetRepositoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRepositoryResponse) GetRepositoryDetail() *components.RepositoryDetail {
	if g == nil {
		return nil
	}
	return g.RepositoryDetail
}
