// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetReleaseRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organization_id"`
	RepositoryID   string `pathParam:"style=simple,explode=false,name=repository_id"`
	ReleaseID      string `pathParam:"style=simple,explode=false,name=release_id"`
}

func (g *GetReleaseRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetReleaseRequest) GetRepositoryID() string {
	if g == nil {
		return ""
	}
	return g.RepositoryID
}

func (g *GetReleaseRequest) GetReleaseID() string {
	if g == nil {
		return ""
	}
	return g.ReleaseID
}

type GetReleaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ReleaseDetail *components.ReleaseDetail
}

func (g *GetReleaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetReleaseResponse) GetReleaseDetail() *components.ReleaseDetail {
	if g == nil {
		return nil
	}
	return g.ReleaseDetail
}
