// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetSponsorRequest struct {
	SponsorID string `pathParam:"style=simple,explode=false,name=sponsor_id"`
}

func (g *GetSponsorRequest) GetSponsorID() string {
	if g == nil {
		return ""
	}
	return g.SponsorID
}

type GetSponsorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SponsorDetail *components.SponsorDetail
}

func (g *GetSponsorResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSponsorResponse) GetSponsorDetail() *components.SponsorDetail {
	if g == nil {
		return nil
	}
	return g.SponsorDetail
}
