// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetSponsorRequest struct {
	SponsorKey string `pathParam:"style=simple,explode=false,name=sponsor_key"`
}

func (g *GetSponsorRequest) GetSponsorKey() string {
	if g == nil {
		return ""
	}
	return g.SponsorKey
}

type GetSponsorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SponsorSchema *components.SponsorSchema
}

func (g *GetSponsorResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSponsorResponse) GetSponsorSchema() *components.SponsorSchema {
	if g == nil {
		return nil
	}
	return g.SponsorSchema
}
