// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/owasp/nest-sdk/models/components"
)

type GetSnapshotRequest struct {
	SnapshotID string `pathParam:"style=simple,explode=false,name=snapshot_id"`
}

func (g *GetSnapshotRequest) GetSnapshotID() string {
	if g == nil {
		return ""
	}
	return g.SnapshotID
}

type GetSnapshotResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SnapshotDetail *components.SnapshotDetail
}

func (g *GetSnapshotResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSnapshotResponse) GetSnapshotDetail() *components.SnapshotDetail {
	if g == nil {
		return nil
	}
	return g.SnapshotDetail
}
