// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListEventsOrdering - Ordering field
type ListEventsOrdering string

const (
	ListEventsOrderingStartDate      ListEventsOrdering = "start_date"
	ListEventsOrderingMinusStartDate ListEventsOrdering = "-start_date"
	ListEventsOrderingEndDate        ListEventsOrdering = "end_date"
	ListEventsOrderingMinusEndDate   ListEventsOrdering = "-end_date"
	ListEventsOrderingLatitude       ListEventsOrdering = "latitude"
	ListEventsOrderingMinusLatitude  ListEventsOrdering = "-latitude"
	ListEventsOrderingLongitude      ListEventsOrdering = "longitude"
	ListEventsOrderingMinusLongitude ListEventsOrdering = "-longitude"
)

func (e ListEventsOrdering) ToPointer() *ListEventsOrdering {
	return &e
}
func (e *ListEventsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start_date":
		fallthrough
	case "-start_date":
		fallthrough
	case "end_date":
		fallthrough
	case "-end_date":
		fallthrough
	case "latitude":
		fallthrough
	case "-latitude":
		fallthrough
	case "longitude":
		fallthrough
	case "-longitude":
		*e = ListEventsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListEventsOrdering: %v", v)
	}
}

type ListEventsRequest struct {
	// Latitude greater than or equal to
	LatitudeGte *float64 `queryParam:"style=form,explode=true,name=latitude_gte"`
	// Latitude less than or equal to
	LatitudeLte *float64 `queryParam:"style=form,explode=true,name=latitude_lte"`
	// Longitude greater than or equal to
	LongitudeGte *float64 `queryParam:"style=form,explode=true,name=longitude_gte"`
	// Longitude less than or equal to
	LongitudeLte *float64 `queryParam:"style=form,explode=true,name=longitude_lte"`
	// Ordering field
	Ordering *ListEventsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Filter for upcoming events
	IsUpcoming *bool `queryParam:"style=form,explode=true,name=is_upcoming"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsRequest) GetLatitudeGte() *float64 {
	if l == nil {
		return nil
	}
	return l.LatitudeGte
}

func (l *ListEventsRequest) GetLatitudeLte() *float64 {
	if l == nil {
		return nil
	}
	return l.LatitudeLte
}

func (l *ListEventsRequest) GetLongitudeGte() *float64 {
	if l == nil {
		return nil
	}
	return l.LongitudeGte
}

func (l *ListEventsRequest) GetLongitudeLte() *float64 {
	if l == nil {
		return nil
	}
	return l.LongitudeLte
}

func (l *ListEventsRequest) GetOrdering() *ListEventsOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListEventsRequest) GetIsUpcoming() *bool {
	if l == nil {
		return nil
	}
	return l.IsUpcoming
}

func (l *ListEventsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListEventsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedEvent *components.PagedEvent
}

func (l *ListEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListEventsResponse) GetPagedEvent() *components.PagedEvent {
	if l == nil {
		return nil
	}
	return l.PagedEvent
}
