// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListSnapshotChaptersOrdering - Ordering field
type ListSnapshotChaptersOrdering string

const (
	ListSnapshotChaptersOrderingCreatedAt      ListSnapshotChaptersOrdering = "created_at"
	ListSnapshotChaptersOrderingMinusCreatedAt ListSnapshotChaptersOrdering = "-created_at"
	ListSnapshotChaptersOrderingUpdatedAt      ListSnapshotChaptersOrdering = "updated_at"
	ListSnapshotChaptersOrderingMinusUpdatedAt ListSnapshotChaptersOrdering = "-updated_at"
)

func (e ListSnapshotChaptersOrdering) ToPointer() *ListSnapshotChaptersOrdering {
	return &e
}
func (e *ListSnapshotChaptersOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListSnapshotChaptersOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSnapshotChaptersOrdering: %v", v)
	}
}

type ListSnapshotChaptersRequest struct {
	SnapshotID string `pathParam:"style=simple,explode=false,name=snapshot_id"`
	// Ordering field
	Ordering *ListSnapshotChaptersOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListSnapshotChaptersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSnapshotChaptersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSnapshotChaptersRequest) GetSnapshotID() string {
	if l == nil {
		return ""
	}
	return l.SnapshotID
}

func (l *ListSnapshotChaptersRequest) GetOrdering() *ListSnapshotChaptersOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListSnapshotChaptersRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSnapshotChaptersRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSnapshotChaptersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedChapter *components.PagedChapter
}

func (l *ListSnapshotChaptersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSnapshotChaptersResponse) GetPagedChapter() *components.PagedChapter {
	if l == nil {
		return nil
	}
	return l.PagedChapter
}
