// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListIssuesOrdering - Ordering field
type ListIssuesOrdering string

const (
	ListIssuesOrderingCreatedAt      ListIssuesOrdering = "created_at"
	ListIssuesOrderingMinusCreatedAt ListIssuesOrdering = "-created_at"
	ListIssuesOrderingUpdatedAt      ListIssuesOrdering = "updated_at"
	ListIssuesOrderingMinusUpdatedAt ListIssuesOrdering = "-updated_at"
)

func (e ListIssuesOrdering) ToPointer() *ListIssuesOrdering {
	return &e
}
func (e *ListIssuesOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListIssuesOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListIssuesOrdering: %v", v)
	}
}

type ListIssuesRequest struct {
	// State of the issue
	State *components.State `queryParam:"style=form,explode=true,name=state"`
	// Ordering field
	Ordering *ListIssuesOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64              `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64              `queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListIssuesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListIssuesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListIssuesRequest) GetState() *components.State {
	if l == nil {
		return nil
	}
	return l.State
}

func (l *ListIssuesRequest) GetOrdering() *ListIssuesOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListIssuesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListIssuesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListIssuesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedIssueSchema *components.PagedIssueSchema
}

func (l *ListIssuesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListIssuesResponse) GetPagedIssueSchema() *components.PagedIssueSchema {
	if l == nil {
		return nil
	}
	return l.PagedIssueSchema
}
