// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListReleasesOrdering - Ordering field
type ListReleasesOrdering string

const (
	ListReleasesOrderingCreatedAt        ListReleasesOrdering = "created_at"
	ListReleasesOrderingMinusCreatedAt   ListReleasesOrdering = "-created_at"
	ListReleasesOrderingPublishedAt      ListReleasesOrdering = "published_at"
	ListReleasesOrderingMinusPublishedAt ListReleasesOrdering = "-published_at"
)

func (e ListReleasesOrdering) ToPointer() *ListReleasesOrdering {
	return &e
}
func (e *ListReleasesOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "published_at":
		fallthrough
	case "-published_at":
		*e = ListReleasesOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListReleasesOrdering: %v", v)
	}
}

type ListReleasesRequest struct {
	// Organization that releases belong to (filtered by repository owner)
	Organization *string `queryParam:"style=form,explode=true,name=organization"`
	// Repository that releases belong to
	Repository *string `queryParam:"style=form,explode=true,name=repository"`
	// Tag name of the release
	TagName *string `queryParam:"style=form,explode=true,name=tag_name"`
	// Ordering field
	Ordering *ListReleasesOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListReleasesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListReleasesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListReleasesRequest) GetOrganization() *string {
	if l == nil {
		return nil
	}
	return l.Organization
}

func (l *ListReleasesRequest) GetRepository() *string {
	if l == nil {
		return nil
	}
	return l.Repository
}

func (l *ListReleasesRequest) GetTagName() *string {
	if l == nil {
		return nil
	}
	return l.TagName
}

func (l *ListReleasesRequest) GetOrdering() *ListReleasesOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListReleasesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListReleasesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListReleasesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedRelease *components.PagedRelease
}

func (l *ListReleasesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListReleasesResponse) GetPagedRelease() *components.PagedRelease {
	if l == nil {
		return nil
	}
	return l.PagedRelease
}
