// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListChaptersOrdering - Ordering field
type ListChaptersOrdering string

const (
	ListChaptersOrderingCreatedAt      ListChaptersOrdering = "created_at"
	ListChaptersOrderingMinusCreatedAt ListChaptersOrdering = "-created_at"
	ListChaptersOrderingUpdatedAt      ListChaptersOrdering = "updated_at"
	ListChaptersOrderingMinusUpdatedAt ListChaptersOrdering = "-updated_at"
)

func (e ListChaptersOrdering) ToPointer() *ListChaptersOrdering {
	return &e
}
func (e *ListChaptersOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListChaptersOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListChaptersOrdering: %v", v)
	}
}

type ListChaptersRequest struct {
	// Country of the chapter
	Country *string `queryParam:"style=form,explode=true,name=country"`
	// Region of the chapter
	Region *string `queryParam:"style=form,explode=true,name=region"`
	// Ordering field
	Ordering *ListChaptersOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                `queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListChaptersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListChaptersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ListChaptersRequest) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *ListChaptersRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *ListChaptersRequest) GetOrdering() *ListChaptersOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *ListChaptersRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListChaptersRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type ListChaptersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedChapterSchema *components.PagedChapterSchema
}

func (o *ListChaptersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListChaptersResponse) GetPagedChapterSchema() *components.PagedChapterSchema {
	if o == nil {
		return nil
	}
	return o.PagedChapterSchema
}
