// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListOrganizationsOrdering - Ordering field
type ListOrganizationsOrdering string

const (
	ListOrganizationsOrderingCreatedAt      ListOrganizationsOrdering = "created_at"
	ListOrganizationsOrderingMinusCreatedAt ListOrganizationsOrdering = "-created_at"
	ListOrganizationsOrderingUpdatedAt      ListOrganizationsOrdering = "updated_at"
	ListOrganizationsOrderingMinusUpdatedAt ListOrganizationsOrdering = "-updated_at"
)

func (e ListOrganizationsOrdering) ToPointer() *ListOrganizationsOrdering {
	return &e
}
func (e *ListOrganizationsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListOrganizationsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListOrganizationsOrdering: %v", v)
	}
}

type ListOrganizationsRequest struct {
	// Location of the organization
	Location *string `queryParam:"style=form,explode=true,name=location"`
	// Ordering field
	Ordering *ListOrganizationsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListOrganizationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationsRequest) GetLocation() *string {
	if l == nil {
		return nil
	}
	return l.Location
}

func (l *ListOrganizationsRequest) GetOrdering() *ListOrganizationsOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListOrganizationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListOrganizationsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListOrganizationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedOrganization *components.PagedOrganization
}

func (l *ListOrganizationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOrganizationsResponse) GetPagedOrganization() *components.PagedOrganization {
	if l == nil {
		return nil
	}
	return l.PagedOrganization
}
