// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListChaptersOrdering - Ordering field
type ListChaptersOrdering string

const (
	ListChaptersOrderingCreatedAt      ListChaptersOrdering = "created_at"
	ListChaptersOrderingMinusCreatedAt ListChaptersOrdering = "-created_at"
	ListChaptersOrderingUpdatedAt      ListChaptersOrdering = "updated_at"
	ListChaptersOrderingMinusUpdatedAt ListChaptersOrdering = "-updated_at"
	ListChaptersOrderingLatitude       ListChaptersOrdering = "latitude"
	ListChaptersOrderingMinusLatitude  ListChaptersOrdering = "-latitude"
	ListChaptersOrderingLongitude      ListChaptersOrdering = "longitude"
	ListChaptersOrderingMinusLongitude ListChaptersOrdering = "-longitude"
)

func (e ListChaptersOrdering) ToPointer() *ListChaptersOrdering {
	return &e
}
func (e *ListChaptersOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		fallthrough
	case "latitude":
		fallthrough
	case "-latitude":
		fallthrough
	case "longitude":
		fallthrough
	case "-longitude":
		*e = ListChaptersOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListChaptersOrdering: %v", v)
	}
}

type ListChaptersRequest struct {
	// Latitude greater than or equal to
	LatitudeGte *float64 `queryParam:"style=form,explode=true,name=latitude_gte"`
	// Latitude less than or equal to
	LatitudeLte *float64 `queryParam:"style=form,explode=true,name=latitude_lte"`
	// Longitude greater than or equal to
	LongitudeGte *float64 `queryParam:"style=form,explode=true,name=longitude_gte"`
	// Longitude less than or equal to
	LongitudeLte *float64 `queryParam:"style=form,explode=true,name=longitude_lte"`
	// Country of the chapter
	Country *string `queryParam:"style=form,explode=true,name=country"`
	// Ordering field
	Ordering *ListChaptersOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListChaptersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListChaptersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListChaptersRequest) GetLatitudeGte() *float64 {
	if l == nil {
		return nil
	}
	return l.LatitudeGte
}

func (l *ListChaptersRequest) GetLatitudeLte() *float64 {
	if l == nil {
		return nil
	}
	return l.LatitudeLte
}

func (l *ListChaptersRequest) GetLongitudeGte() *float64 {
	if l == nil {
		return nil
	}
	return l.LongitudeGte
}

func (l *ListChaptersRequest) GetLongitudeLte() *float64 {
	if l == nil {
		return nil
	}
	return l.LongitudeLte
}

func (l *ListChaptersRequest) GetCountry() *string {
	if l == nil {
		return nil
	}
	return l.Country
}

func (l *ListChaptersRequest) GetOrdering() *ListChaptersOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListChaptersRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListChaptersRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListChaptersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedChapter *components.PagedChapter
}

func (l *ListChaptersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListChaptersResponse) GetPagedChapter() *components.PagedChapter {
	if l == nil {
		return nil
	}
	return l.PagedChapter
}
