// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListSnapshotReleasesOrdering - Ordering field
type ListSnapshotReleasesOrdering string

const (
	ListSnapshotReleasesOrderingCreatedAt        ListSnapshotReleasesOrdering = "created_at"
	ListSnapshotReleasesOrderingMinusCreatedAt   ListSnapshotReleasesOrdering = "-created_at"
	ListSnapshotReleasesOrderingPublishedAt      ListSnapshotReleasesOrdering = "published_at"
	ListSnapshotReleasesOrderingMinusPublishedAt ListSnapshotReleasesOrdering = "-published_at"
)

func (e ListSnapshotReleasesOrdering) ToPointer() *ListSnapshotReleasesOrdering {
	return &e
}
func (e *ListSnapshotReleasesOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "published_at":
		fallthrough
	case "-published_at":
		*e = ListSnapshotReleasesOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSnapshotReleasesOrdering: %v", v)
	}
}

type ListSnapshotReleasesRequest struct {
	SnapshotID string `pathParam:"style=simple,explode=false,name=snapshot_id"`
	// Ordering field
	Ordering *ListSnapshotReleasesOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListSnapshotReleasesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSnapshotReleasesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSnapshotReleasesRequest) GetSnapshotID() string {
	if l == nil {
		return ""
	}
	return l.SnapshotID
}

func (l *ListSnapshotReleasesRequest) GetOrdering() *ListSnapshotReleasesOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListSnapshotReleasesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSnapshotReleasesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSnapshotReleasesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedSnapshotRelease *components.PagedSnapshotRelease
}

func (l *ListSnapshotReleasesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSnapshotReleasesResponse) GetPagedSnapshotRelease() *components.PagedSnapshotRelease {
	if l == nil {
		return nil
	}
	return l.PagedSnapshotRelease
}
