// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListSnapshotMembersOrdering - Ordering field
type ListSnapshotMembersOrdering string

const (
	ListSnapshotMembersOrderingCreatedAt      ListSnapshotMembersOrdering = "created_at"
	ListSnapshotMembersOrderingMinusCreatedAt ListSnapshotMembersOrdering = "-created_at"
	ListSnapshotMembersOrderingUpdatedAt      ListSnapshotMembersOrdering = "updated_at"
	ListSnapshotMembersOrderingMinusUpdatedAt ListSnapshotMembersOrdering = "-updated_at"
)

func (e ListSnapshotMembersOrdering) ToPointer() *ListSnapshotMembersOrdering {
	return &e
}
func (e *ListSnapshotMembersOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListSnapshotMembersOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSnapshotMembersOrdering: %v", v)
	}
}

type ListSnapshotMembersRequest struct {
	SnapshotID string `pathParam:"style=simple,explode=false,name=snapshot_id"`
	// Ordering field
	Ordering *ListSnapshotMembersOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListSnapshotMembersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSnapshotMembersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSnapshotMembersRequest) GetSnapshotID() string {
	if l == nil {
		return ""
	}
	return l.SnapshotID
}

func (l *ListSnapshotMembersRequest) GetOrdering() *ListSnapshotMembersOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListSnapshotMembersRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSnapshotMembersRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSnapshotMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedMember *components.PagedMember
}

func (l *ListSnapshotMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSnapshotMembersResponse) GetPagedMember() *components.PagedMember {
	if l == nil {
		return nil
	}
	return l.PagedMember
}
