// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListEventsOrdering - Ordering field
type ListEventsOrdering string

const (
	ListEventsOrderingStartDate      ListEventsOrdering = "start_date"
	ListEventsOrderingMinusStartDate ListEventsOrdering = "-start_date"
	ListEventsOrderingEndDate        ListEventsOrdering = "end_date"
	ListEventsOrderingMinusEndDate   ListEventsOrdering = "-end_date"
)

func (e ListEventsOrdering) ToPointer() *ListEventsOrdering {
	return &e
}
func (e *ListEventsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start_date":
		fallthrough
	case "-start_date":
		fallthrough
	case "end_date":
		fallthrough
	case "-end_date":
		*e = ListEventsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListEventsOrdering: %v", v)
	}
}

type ListEventsRequest struct {
	// Ordering field
	Ordering *ListEventsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsRequest) GetOrdering() *ListEventsOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListEventsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListEventsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedEvent *components.PagedEvent
}

func (l *ListEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListEventsResponse) GetPagedEvent() *components.PagedEvent {
	if l == nil {
		return nil
	}
	return l.PagedEvent
}
