// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

type ListMilestonesOrdering string

const (
	ListMilestonesOrderingCreatedAt      ListMilestonesOrdering = "created_at"
	ListMilestonesOrderingMinusCreatedAt ListMilestonesOrdering = "-created_at"
	ListMilestonesOrderingUpdatedAt      ListMilestonesOrdering = "updated_at"
	ListMilestonesOrderingMinusUpdatedAt ListMilestonesOrdering = "-updated_at"
)

func (e ListMilestonesOrdering) ToPointer() *ListMilestonesOrdering {
	return &e
}
func (e *ListMilestonesOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListMilestonesOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListMilestonesOrdering: %v", v)
	}
}

type ListMilestonesRequest struct {
	// Organization that milestones belong to (filtered by repository owner)
	Organization *string `queryParam:"style=form,explode=true,name=organization"`
	// Repository that milestones belong to
	Repository *string `queryParam:"style=form,explode=true,name=repository"`
	// Milestone state
	State    *components.State       `queryParam:"style=form,explode=true,name=state"`
	Ordering *ListMilestonesOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListMilestonesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMilestonesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListMilestonesRequest) GetOrganization() *string {
	if l == nil {
		return nil
	}
	return l.Organization
}

func (l *ListMilestonesRequest) GetRepository() *string {
	if l == nil {
		return nil
	}
	return l.Repository
}

func (l *ListMilestonesRequest) GetState() *components.State {
	if l == nil {
		return nil
	}
	return l.State
}

func (l *ListMilestonesRequest) GetOrdering() *ListMilestonesOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListMilestonesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListMilestonesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListMilestonesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedMilestone *components.PagedMilestone
}

func (l *ListMilestonesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListMilestonesResponse) GetPagedMilestone() *components.PagedMilestone {
	if l == nil {
		return nil
	}
	return l.PagedMilestone
}
