// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListSponsorsOrdering - Ordering field
type ListSponsorsOrdering string

const (
	ListSponsorsOrderingName      ListSponsorsOrdering = "name"
	ListSponsorsOrderingMinusName ListSponsorsOrdering = "-name"
)

func (e ListSponsorsOrdering) ToPointer() *ListSponsorsOrdering {
	return &e
}
func (e *ListSponsorsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "name":
		fallthrough
	case "-name":
		*e = ListSponsorsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSponsorsOrdering: %v", v)
	}
}

type ListSponsorsRequest struct {
	// Member status of the sponsor
	IsMember *bool `queryParam:"style=form,explode=true,name=is_member"`
	// Member type of the sponsor
	MemberType *components.MemberType `queryParam:"style=form,explode=true,name=member_type"`
	// Filter by the type of sponsorship (e.g., Gold, Silver, Platinum).
	SponsorType *string `queryParam:"style=form,explode=true,name=sponsor_type"`
	// Ordering field
	Ordering *ListSponsorsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListSponsorsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSponsorsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSponsorsRequest) GetIsMember() *bool {
	if l == nil {
		return nil
	}
	return l.IsMember
}

func (l *ListSponsorsRequest) GetMemberType() *components.MemberType {
	if l == nil {
		return nil
	}
	return l.MemberType
}

func (l *ListSponsorsRequest) GetSponsorType() *string {
	if l == nil {
		return nil
	}
	return l.SponsorType
}

func (l *ListSponsorsRequest) GetOrdering() *ListSponsorsOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListSponsorsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSponsorsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSponsorsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedSponsor *components.PagedSponsor
}

func (l *ListSponsorsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSponsorsResponse) GetPagedSponsor() *components.PagedSponsor {
	if l == nil {
		return nil
	}
	return l.PagedSponsor
}
