// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListSnapshotsOrdering - Ordering field
type ListSnapshotsOrdering string

const (
	ListSnapshotsOrderingCreatedAt      ListSnapshotsOrdering = "created_at"
	ListSnapshotsOrderingMinusCreatedAt ListSnapshotsOrdering = "-created_at"
	ListSnapshotsOrderingUpdatedAt      ListSnapshotsOrdering = "updated_at"
	ListSnapshotsOrderingMinusUpdatedAt ListSnapshotsOrdering = "-updated_at"
	ListSnapshotsOrderingStartAt        ListSnapshotsOrdering = "start_at"
	ListSnapshotsOrderingMinusStartAt   ListSnapshotsOrdering = "-start_at"
)

func (e ListSnapshotsOrdering) ToPointer() *ListSnapshotsOrdering {
	return &e
}
func (e *ListSnapshotsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		fallthrough
	case "start_at":
		fallthrough
	case "-start_at":
		*e = ListSnapshotsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSnapshotsOrdering: %v", v)
	}
}

type ListSnapshotsRequest struct {
	// Ordering field
	Ordering *ListSnapshotsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListSnapshotsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSnapshotsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSnapshotsRequest) GetOrdering() *ListSnapshotsOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListSnapshotsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSnapshotsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSnapshotsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedSnapshot *components.PagedSnapshot
}

func (l *ListSnapshotsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSnapshotsResponse) GetPagedSnapshot() *components.PagedSnapshot {
	if l == nil {
		return nil
	}
	return l.PagedSnapshot
}
