// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListMembersOrdering - Ordering field
type ListMembersOrdering string

const (
	ListMembersOrderingCreatedAt      ListMembersOrdering = "created_at"
	ListMembersOrderingMinusCreatedAt ListMembersOrdering = "-created_at"
	ListMembersOrderingUpdatedAt      ListMembersOrdering = "updated_at"
	ListMembersOrderingMinusUpdatedAt ListMembersOrdering = "-updated_at"
)

func (e ListMembersOrdering) ToPointer() *ListMembersOrdering {
	return &e
}
func (e *ListMembersOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListMembersOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListMembersOrdering: %v", v)
	}
}

type ListMembersRequest struct {
	// Company of the user
	Company *string `queryParam:"style=form,explode=true,name=company"`
	// Location of the member
	Location *string `queryParam:"style=form,explode=true,name=location"`
	// Ordering field
	Ordering *ListMembersOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListMembersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMembersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListMembersRequest) GetCompany() *string {
	if l == nil {
		return nil
	}
	return l.Company
}

func (l *ListMembersRequest) GetLocation() *string {
	if l == nil {
		return nil
	}
	return l.Location
}

func (l *ListMembersRequest) GetOrdering() *ListMembersOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListMembersRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListMembersRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedMember *components.PagedMember
}

func (l *ListMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListMembersResponse) GetPagedMember() *components.PagedMember {
	if l == nil {
		return nil
	}
	return l.PagedMember
}
