// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListSnapshotIssuesOrdering - Ordering field
type ListSnapshotIssuesOrdering string

const (
	ListSnapshotIssuesOrderingCreatedAt      ListSnapshotIssuesOrdering = "created_at"
	ListSnapshotIssuesOrderingMinusCreatedAt ListSnapshotIssuesOrdering = "-created_at"
	ListSnapshotIssuesOrderingUpdatedAt      ListSnapshotIssuesOrdering = "updated_at"
	ListSnapshotIssuesOrderingMinusUpdatedAt ListSnapshotIssuesOrdering = "-updated_at"
)

func (e ListSnapshotIssuesOrdering) ToPointer() *ListSnapshotIssuesOrdering {
	return &e
}
func (e *ListSnapshotIssuesOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListSnapshotIssuesOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSnapshotIssuesOrdering: %v", v)
	}
}

type ListSnapshotIssuesRequest struct {
	SnapshotID string `pathParam:"style=simple,explode=false,name=snapshot_id"`
	// Ordering field
	Ordering *ListSnapshotIssuesOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListSnapshotIssuesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSnapshotIssuesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"snapshot_id"}); err != nil {
		return err
	}
	return nil
}

func (l *ListSnapshotIssuesRequest) GetSnapshotID() string {
	if l == nil {
		return ""
	}
	return l.SnapshotID
}

func (l *ListSnapshotIssuesRequest) GetOrdering() *ListSnapshotIssuesOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListSnapshotIssuesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSnapshotIssuesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSnapshotIssuesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedSnapshotIssue *components.PagedSnapshotIssue
}

func (l *ListSnapshotIssuesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSnapshotIssuesResponse) GetPagedSnapshotIssue() *components.PagedSnapshotIssue {
	if l == nil {
		return nil
	}
	return l.PagedSnapshotIssue
}
