// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListOrganizationsOrdering - Ordering field
type ListOrganizationsOrdering string

const (
	ListOrganizationsOrderingCreatedAt      ListOrganizationsOrdering = "created_at"
	ListOrganizationsOrderingMinusCreatedAt ListOrganizationsOrdering = "-created_at"
	ListOrganizationsOrderingUpdatedAt      ListOrganizationsOrdering = "updated_at"
	ListOrganizationsOrderingMinusUpdatedAt ListOrganizationsOrdering = "-updated_at"
)

func (e ListOrganizationsOrdering) ToPointer() *ListOrganizationsOrdering {
	return &e
}
func (e *ListOrganizationsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListOrganizationsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListOrganizationsOrdering: %v", v)
	}
}

type ListOrganizationsRequest struct {
	// Location of the organization
	Location *string `queryParam:"style=form,explode=true,name=location"`
	// Ordering field
	Ordering *ListOrganizationsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                     `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                     `queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListOrganizationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ListOrganizationsRequest) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *ListOrganizationsRequest) GetOrdering() *ListOrganizationsOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *ListOrganizationsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListOrganizationsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type ListOrganizationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedOrganizationSchema *components.PagedOrganizationSchema
}

func (o *ListOrganizationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListOrganizationsResponse) GetPagedOrganizationSchema() *components.PagedOrganizationSchema {
	if o == nil {
		return nil
	}
	return o.PagedOrganizationSchema
}
