// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListSnapshotProjectsOrdering - Ordering field
type ListSnapshotProjectsOrdering string

const (
	ListSnapshotProjectsOrderingCreatedAt      ListSnapshotProjectsOrdering = "created_at"
	ListSnapshotProjectsOrderingMinusCreatedAt ListSnapshotProjectsOrdering = "-created_at"
	ListSnapshotProjectsOrderingUpdatedAt      ListSnapshotProjectsOrdering = "updated_at"
	ListSnapshotProjectsOrderingMinusUpdatedAt ListSnapshotProjectsOrdering = "-updated_at"
)

func (e ListSnapshotProjectsOrdering) ToPointer() *ListSnapshotProjectsOrdering {
	return &e
}
func (e *ListSnapshotProjectsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListSnapshotProjectsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSnapshotProjectsOrdering: %v", v)
	}
}

type ListSnapshotProjectsRequest struct {
	SnapshotID string `pathParam:"style=simple,explode=false,name=snapshot_id"`
	// Ordering field
	Ordering *ListSnapshotProjectsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"100" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListSnapshotProjectsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSnapshotProjectsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"snapshot_id"}); err != nil {
		return err
	}
	return nil
}

func (l *ListSnapshotProjectsRequest) GetSnapshotID() string {
	if l == nil {
		return ""
	}
	return l.SnapshotID
}

func (l *ListSnapshotProjectsRequest) GetOrdering() *ListSnapshotProjectsOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListSnapshotProjectsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListSnapshotProjectsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListSnapshotProjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedProject *components.PagedProject
}

func (l *ListSnapshotProjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSnapshotProjectsResponse) GetPagedProject() *components.PagedProject {
	if l == nil {
		return nil
	}
	return l.PagedProject
}
