// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListReleasesOrdering - Ordering field
type ListReleasesOrdering string

const (
	ListReleasesOrderingCreatedAt        ListReleasesOrdering = "created_at"
	ListReleasesOrderingMinusCreatedAt   ListReleasesOrdering = "-created_at"
	ListReleasesOrderingPublishedAt      ListReleasesOrdering = "published_at"
	ListReleasesOrderingMinusPublishedAt ListReleasesOrdering = "-published_at"
)

func (e ListReleasesOrdering) ToPointer() *ListReleasesOrdering {
	return &e
}
func (e *ListReleasesOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "published_at":
		fallthrough
	case "-published_at":
		*e = ListReleasesOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListReleasesOrdering: %v", v)
	}
}

type ListReleasesRequest struct {
	// Tag name of the release
	TagName *string `queryParam:"style=form,explode=true,name=tag_name"`
	// Ordering field
	Ordering *ListReleasesOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                `queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListReleasesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListReleasesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ListReleasesRequest) GetTagName() *string {
	if o == nil {
		return nil
	}
	return o.TagName
}

func (o *ListReleasesRequest) GetOrdering() *ListReleasesOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *ListReleasesRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListReleasesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type ListReleasesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedReleaseSchema *components.PagedReleaseSchema
}

func (o *ListReleasesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListReleasesResponse) GetPagedReleaseSchema() *components.PagedReleaseSchema {
	if o == nil {
		return nil
	}
	return o.PagedReleaseSchema
}
