// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListEventsOrdering - Ordering field
type ListEventsOrdering string

const (
	ListEventsOrderingStartDate      ListEventsOrdering = "start_date"
	ListEventsOrderingMinusStartDate ListEventsOrdering = "-start_date"
	ListEventsOrderingEndDate        ListEventsOrdering = "end_date"
	ListEventsOrderingMinusEndDate   ListEventsOrdering = "-end_date"
)

func (e ListEventsOrdering) ToPointer() *ListEventsOrdering {
	return &e
}
func (e *ListEventsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start_date":
		fallthrough
	case "-start_date":
		fallthrough
	case "end_date":
		fallthrough
	case "-end_date":
		*e = ListEventsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListEventsOrdering: %v", v)
	}
}

type ListEventsRequest struct {
	// Ordering field
	Ordering *ListEventsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64              `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64              `queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ListEventsRequest) GetOrdering() *ListEventsOrdering {
	if o == nil {
		return nil
	}
	return o.Ordering
}

func (o *ListEventsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListEventsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type ListEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedEventSchema *components.PagedEventSchema
}

func (o *ListEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListEventsResponse) GetPagedEventSchema() *components.PagedEventSchema {
	if o == nil {
		return nil
	}
	return o.PagedEventSchema
}
