// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListCommitteesOrdering - Ordering field
type ListCommitteesOrdering string

const (
	ListCommitteesOrderingCreatedAt      ListCommitteesOrdering = "created_at"
	ListCommitteesOrderingMinusCreatedAt ListCommitteesOrdering = "-created_at"
	ListCommitteesOrderingUpdatedAt      ListCommitteesOrdering = "updated_at"
	ListCommitteesOrderingMinusUpdatedAt ListCommitteesOrdering = "-updated_at"
)

func (e ListCommitteesOrdering) ToPointer() *ListCommitteesOrdering {
	return &e
}
func (e *ListCommitteesOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListCommitteesOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListCommitteesOrdering: %v", v)
	}
}

type ListCommitteesRequest struct {
	// Ordering field
	Ordering *ListCommitteesOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                  `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                  `queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListCommitteesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCommitteesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCommitteesRequest) GetOrdering() *ListCommitteesOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListCommitteesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListCommitteesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListCommitteesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedCommitteeSchema *components.PagedCommitteeSchema
}

func (l *ListCommitteesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCommitteesResponse) GetPagedCommitteeSchema() *components.PagedCommitteeSchema {
	if l == nil {
		return nil
	}
	return l.PagedCommitteeSchema
}
