// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
	"github.com/owasp/nest-sdk/models/components"
)

// ListProjectsOrdering - Ordering field
type ListProjectsOrdering string

const (
	ListProjectsOrderingCreatedAt      ListProjectsOrdering = "created_at"
	ListProjectsOrderingMinusCreatedAt ListProjectsOrdering = "-created_at"
	ListProjectsOrderingUpdatedAt      ListProjectsOrdering = "updated_at"
	ListProjectsOrderingMinusUpdatedAt ListProjectsOrdering = "-updated_at"
)

func (e ListProjectsOrdering) ToPointer() *ListProjectsOrdering {
	return &e
}
func (e *ListProjectsOrdering) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created_at":
		fallthrough
	case "-created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "-updated_at":
		*e = ListProjectsOrdering(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListProjectsOrdering: %v", v)
	}
}

type ListProjectsRequest struct {
	// Level of the project
	Level *components.ProjectLevel `queryParam:"style=form,explode=true,name=level"`
	// Ordering field
	Ordering *ListProjectsOrdering `queryParam:"style=form,explode=true,name=ordering"`
	Page     *int64                `default:"1" queryParam:"style=form,explode=true,name=page"`
	PageSize *int64                `queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListProjectsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListProjectsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListProjectsRequest) GetLevel() *components.ProjectLevel {
	if l == nil {
		return nil
	}
	return l.Level
}

func (l *ListProjectsRequest) GetOrdering() *ListProjectsOrdering {
	if l == nil {
		return nil
	}
	return l.Ordering
}

func (l *ListProjectsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListProjectsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListProjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PagedProjectSchema *components.PagedProjectSchema
}

func (l *ListProjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListProjectsResponse) GetPagedProjectSchema() *components.PagedProjectSchema {
	if l == nil {
		return nil
	}
	return l.PagedProjectSchema
}
