// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Category - Event category.
type Category string

const (
	CategoryAppsecDays Category = "appsec_days"
	CategoryGlobal     Category = "global"
	CategoryOther      Category = "other"
	CategoryPartner    Category = "partner"
)

func (e Category) ToPointer() *Category {
	return &e
}
func (e *Category) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "appsec_days":
		fallthrough
	case "global":
		fallthrough
	case "other":
		fallthrough
	case "partner":
		*e = Category(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Category: %v", v)
	}
}
