// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// ChapterDetail - Detail schema for Chapter (used in single item endpoints).
type ChapterDetail struct {
	CreatedAt time.Time `json:"created_at"`
	Key       string    `json:"key"`
	Latitude  *float64  `json:"latitude,omitempty"`
	Longitude *float64  `json:"longitude,omitempty"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	Country   string    `json:"country"`
	Region    string    `json:"region"`
}

func (c ChapterDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChapterDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"created_at", "key", "name", "updated_at", "country", "region"}); err != nil {
		return err
	}
	return nil
}

func (c *ChapterDetail) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ChapterDetail) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *ChapterDetail) GetLatitude() *float64 {
	if c == nil {
		return nil
	}
	return c.Latitude
}

func (c *ChapterDetail) GetLongitude() *float64 {
	if c == nil {
		return nil
	}
	return c.Longitude
}

func (c *ChapterDetail) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ChapterDetail) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *ChapterDetail) GetCountry() string {
	if c == nil {
		return ""
	}
	return c.Country
}

func (c *ChapterDetail) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}
