// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// ChapterSchema - Schema for Chapter.
type ChapterSchema struct {
	Country   string    `json:"country"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	Region    string    `json:"region"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (c ChapterSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChapterSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"country", "created_at", "name", "region", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (c *ChapterSchema) GetCountry() string {
	if c == nil {
		return ""
	}
	return c.Country
}

func (c *ChapterSchema) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *ChapterSchema) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ChapterSchema) GetRegion() string {
	if c == nil {
		return ""
	}
	return c.Region
}

func (c *ChapterSchema) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}
