// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Chapter - Schema for Chapter (minimal fields for list display).
type Chapter struct {
	CreatedAt time.Time `json:"created_at"`
	Key       string    `json:"key"`
	Latitude  *float64  `json:"latitude,omitempty"`
	Longitude *float64  `json:"longitude,omitempty"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (c Chapter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Chapter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"created_at", "key", "name", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (c *Chapter) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Chapter) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *Chapter) GetLatitude() *float64 {
	if c == nil {
		return nil
	}
	return c.Latitude
}

func (c *Chapter) GetLongitude() *float64 {
	if c == nil {
		return nil
	}
	return c.Longitude
}

func (c *Chapter) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Chapter) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}
