// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// CommitteeDetail - Detail schema for Committee (used in single item endpoints).
type CommitteeDetail struct {
	CreatedAt   time.Time `json:"created_at"`
	Key         string    `json:"key"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
	Description string    `json:"description"`
}

func (c CommitteeDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CommitteeDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CommitteeDetail) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CommitteeDetail) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *CommitteeDetail) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CommitteeDetail) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CommitteeDetail) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}
