// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// CommitteeSchema - Schema for Committee.
type CommitteeSchema struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (c CommitteeSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CommitteeSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name", "description", "created_at", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (c *CommitteeSchema) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CommitteeSchema) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CommitteeSchema) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CommitteeSchema) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}
