// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Committee - Schema for Committee (minimal fields for list display).
type Committee struct {
	CreatedAt time.Time `json:"created_at"`
	Key       string    `json:"key"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (c Committee) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Committee) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Committee) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Committee) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *Committee) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Committee) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}
