// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Event - Schema for Event (minimal fields for list display).
type Event struct {
	EndDate   *time.Time `json:"end_date,omitempty"`
	Key       string     `json:"key"`
	Latitude  *float64   `json:"latitude,omitempty"`
	Longitude *float64   `json:"longitude,omitempty"`
	Name      string     `json:"name"`
	StartDate time.Time  `json:"start_date"`
	URL       *string    `json:"url,omitempty"`
}

func (e Event) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Event) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"key", "name", "start_date"}); err != nil {
		return err
	}
	return nil
}

func (e *Event) GetEndDate() *time.Time {
	if e == nil {
		return nil
	}
	return e.EndDate
}

func (e *Event) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *Event) GetLatitude() *float64 {
	if e == nil {
		return nil
	}
	return e.Latitude
}

func (e *Event) GetLongitude() *float64 {
	if e == nil {
		return nil
	}
	return e.Longitude
}

func (e *Event) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *Event) GetStartDate() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.StartDate
}

func (e *Event) GetURL() *string {
	if e == nil {
		return nil
	}
	return e.URL
}
