// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// EventSchema - Schema for Event.
type EventSchema struct {
	Description string    `json:"description"`
	Name        string    `json:"name"`
	EndDate     time.Time `json:"end_date"`
	StartDate   time.Time `json:"start_date"`
	URL         string    `json:"url"`
}

func (e EventSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"description", "name", "end_date", "start_date", "url"}); err != nil {
		return err
	}
	return nil
}

func (e *EventSchema) GetDescription() string {
	if e == nil {
		return ""
	}
	return e.Description
}

func (e *EventSchema) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EventSchema) GetEndDate() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.EndDate
}

func (e *EventSchema) GetStartDate() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.StartDate
}

func (e *EventSchema) GetURL() string {
	if e == nil {
		return ""
	}
	return e.URL
}
