// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// EventDetail - Detail schema for Event (used in single item endpoints).
type EventDetail struct {
	EndDate     *time.Time `json:"end_date,omitempty"`
	Key         string     `json:"key"`
	Latitude    *float64   `json:"latitude,omitempty"`
	Longitude   *float64   `json:"longitude,omitempty"`
	Name        string     `json:"name"`
	StartDate   time.Time  `json:"start_date"`
	URL         *string    `json:"url,omitempty"`
	Description *string    `json:"description,omitempty"`
}

func (e EventDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"key", "name", "start_date"}); err != nil {
		return err
	}
	return nil
}

func (e *EventDetail) GetEndDate() *time.Time {
	if e == nil {
		return nil
	}
	return e.EndDate
}

func (e *EventDetail) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EventDetail) GetLatitude() *float64 {
	if e == nil {
		return nil
	}
	return e.Latitude
}

func (e *EventDetail) GetLongitude() *float64 {
	if e == nil {
		return nil
	}
	return e.Longitude
}

func (e *EventDetail) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EventDetail) GetStartDate() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.StartDate
}

func (e *EventDetail) GetURL() *string {
	if e == nil {
		return nil
	}
	return e.URL
}

func (e *EventDetail) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}
