// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Event - Schema for Event (minimal fields for list display).
type Event struct {
	EndDate   *string  `json:"end_date,omitempty"`
	Key       string   `json:"key"`
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
	Name      string   `json:"name"`
	StartDate string   `json:"start_date"`
	URL       *string  `json:"url,omitempty"`
}

func (e *Event) GetEndDate() *string {
	if e == nil {
		return nil
	}
	return e.EndDate
}

func (e *Event) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *Event) GetLatitude() *float64 {
	if e == nil {
		return nil
	}
	return e.Latitude
}

func (e *Event) GetLongitude() *float64 {
	if e == nil {
		return nil
	}
	return e.Longitude
}

func (e *Event) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *Event) GetStartDate() string {
	if e == nil {
		return ""
	}
	return e.StartDate
}

func (e *Event) GetURL() *string {
	if e == nil {
		return nil
	}
	return e.URL
}
