// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// IssueDetail - Detail schema for Issue (used in single item endpoints).
type IssueDetail struct {
	CreatedAt time.Time `json:"created_at"`
	State     State     `json:"state"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	URL       string    `json:"url"`
	Body      string    `json:"body"`
}

func (i IssueDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IssueDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"created_at", "state", "title", "updated_at", "url", "body"}); err != nil {
		return err
	}
	return nil
}

func (i *IssueDetail) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *IssueDetail) GetState() State {
	if i == nil {
		return State("")
	}
	return i.State
}

func (i *IssueDetail) GetTitle() string {
	if i == nil {
		return ""
	}
	return i.Title
}

func (i *IssueDetail) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *IssueDetail) GetURL() string {
	if i == nil {
		return ""
	}
	return i.URL
}

func (i *IssueDetail) GetBody() string {
	if i == nil {
		return ""
	}
	return i.Body
}
