// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// IssueState - Issue state choices.
type IssueState string

const (
	IssueStateOpen   IssueState = "open"
	IssueStateClosed IssueState = "closed"
)

func (e IssueState) ToPointer() *IssueState {
	return &e
}
func (e *IssueState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "open":
		fallthrough
	case "closed":
		*e = IssueState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IssueState: %v", v)
	}
}
