// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// IssueSchema - Schema for Issue.
type IssueSchema struct {
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	Title     string    `json:"title"`
	State     State     `json:"state"`
	UpdatedAt time.Time `json:"updated_at"`
	URL       string    `json:"url"`
}

func (i IssueSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IssueSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"body", "created_at", "title", "state", "updated_at", "url"}); err != nil {
		return err
	}
	return nil
}

func (o *IssueSchema) GetBody() string {
	if o == nil {
		return ""
	}
	return o.Body
}

func (o *IssueSchema) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *IssueSchema) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *IssueSchema) GetState() State {
	if o == nil {
		return State("")
	}
	return o.State
}

func (o *IssueSchema) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *IssueSchema) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
