// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Leader - Schema for Leader.
type Leader struct {
	Key  *string `json:"key,omitempty"`
	Name string  `json:"name"`
}

func (l *Leader) GetKey() *string {
	if l == nil {
		return nil
	}
	return l.Key
}

func (l *Leader) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}
