// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// MemberDetail - Detail schema for Member (used in single item endpoints).
type MemberDetail struct {
	AvatarURL               string    `json:"avatar_url"`
	CreatedAt               time.Time `json:"created_at"`
	Login                   string    `json:"login"`
	Name                    string    `json:"name"`
	UpdatedAt               time.Time `json:"updated_at"`
	URL                     string    `json:"url"`
	Bio                     string    `json:"bio"`
	Company                 string    `json:"company"`
	FollowersCount          int64     `json:"followers_count"`
	FollowingCount          int64     `json:"following_count"`
	Location                string    `json:"location"`
	PublicRepositoriesCount int64     `json:"public_repositories_count"`
	Title                   string    `json:"title"`
	TwitterUsername         string    `json:"twitter_username"`
}

func (m MemberDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MemberDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"avatar_url", "created_at", "login", "name", "updated_at", "url", "bio", "company", "followers_count", "following_count", "location", "public_repositories_count", "title", "twitter_username"}); err != nil {
		return err
	}
	return nil
}

func (m *MemberDetail) GetAvatarURL() string {
	if m == nil {
		return ""
	}
	return m.AvatarURL
}

func (m *MemberDetail) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *MemberDetail) GetLogin() string {
	if m == nil {
		return ""
	}
	return m.Login
}

func (m *MemberDetail) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MemberDetail) GetUpdatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.UpdatedAt
}

func (m *MemberDetail) GetURL() string {
	if m == nil {
		return ""
	}
	return m.URL
}

func (m *MemberDetail) GetBio() string {
	if m == nil {
		return ""
	}
	return m.Bio
}

func (m *MemberDetail) GetCompany() string {
	if m == nil {
		return ""
	}
	return m.Company
}

func (m *MemberDetail) GetFollowersCount() int64 {
	if m == nil {
		return 0
	}
	return m.FollowersCount
}

func (m *MemberDetail) GetFollowingCount() int64 {
	if m == nil {
		return 0
	}
	return m.FollowingCount
}

func (m *MemberDetail) GetLocation() string {
	if m == nil {
		return ""
	}
	return m.Location
}

func (m *MemberDetail) GetPublicRepositoriesCount() int64 {
	if m == nil {
		return 0
	}
	return m.PublicRepositoriesCount
}

func (m *MemberDetail) GetTitle() string {
	if m == nil {
		return ""
	}
	return m.Title
}

func (m *MemberDetail) GetTwitterUsername() string {
	if m == nil {
		return ""
	}
	return m.TwitterUsername
}
