// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type MemberType string

const (
	MemberTypePlatinum MemberType = "Platinum"
	MemberTypeGold     MemberType = "Gold"
	MemberTypeSilver   MemberType = "Silver"
)

func (e MemberType) ToPointer() *MemberType {
	return &e
}
func (e *MemberType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Platinum":
		fallthrough
	case "Gold":
		fallthrough
	case "Silver":
		*e = MemberType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MemberType: %v", v)
	}
}
