// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// MemberSchema - Schema for Member.
type MemberSchema struct {
	AvatarURL               string    `json:"avatar_url"`
	Bio                     string    `json:"bio"`
	Company                 string    `json:"company"`
	CreatedAt               time.Time `json:"created_at"`
	FollowersCount          int64     `json:"followers_count"`
	FollowingCount          int64     `json:"following_count"`
	Location                string    `json:"location"`
	Login                   string    `json:"login"`
	Name                    string    `json:"name"`
	PublicRepositoriesCount int64     `json:"public_repositories_count"`
	Title                   string    `json:"title"`
	TwitterUsername         string    `json:"twitter_username"`
	UpdatedAt               time.Time `json:"updated_at"`
	URL                     string    `json:"url"`
}

func (m MemberSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MemberSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"avatar_url", "bio", "company", "created_at", "followers_count", "following_count", "location", "login", "name", "public_repositories_count", "title", "twitter_username", "updated_at", "url"}); err != nil {
		return err
	}
	return nil
}

func (m *MemberSchema) GetAvatarURL() string {
	if m == nil {
		return ""
	}
	return m.AvatarURL
}

func (m *MemberSchema) GetBio() string {
	if m == nil {
		return ""
	}
	return m.Bio
}

func (m *MemberSchema) GetCompany() string {
	if m == nil {
		return ""
	}
	return m.Company
}

func (m *MemberSchema) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *MemberSchema) GetFollowersCount() int64 {
	if m == nil {
		return 0
	}
	return m.FollowersCount
}

func (m *MemberSchema) GetFollowingCount() int64 {
	if m == nil {
		return 0
	}
	return m.FollowingCount
}

func (m *MemberSchema) GetLocation() string {
	if m == nil {
		return ""
	}
	return m.Location
}

func (m *MemberSchema) GetLogin() string {
	if m == nil {
		return ""
	}
	return m.Login
}

func (m *MemberSchema) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MemberSchema) GetPublicRepositoriesCount() int64 {
	if m == nil {
		return 0
	}
	return m.PublicRepositoriesCount
}

func (m *MemberSchema) GetTitle() string {
	if m == nil {
		return ""
	}
	return m.Title
}

func (m *MemberSchema) GetTwitterUsername() string {
	if m == nil {
		return ""
	}
	return m.TwitterUsername
}

func (m *MemberSchema) GetUpdatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.UpdatedAt
}

func (m *MemberSchema) GetURL() string {
	if m == nil {
		return ""
	}
	return m.URL
}
