// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// MemberSchema - Schema for Member.
type MemberSchema struct {
	AvatarURL               string    `json:"avatar_url"`
	Bio                     string    `json:"bio"`
	Company                 string    `json:"company"`
	CreatedAt               time.Time `json:"created_at"`
	Email                   string    `json:"email"`
	FollowersCount          int64     `json:"followers_count"`
	FollowingCount          int64     `json:"following_count"`
	Location                string    `json:"location"`
	Login                   string    `json:"login"`
	Name                    string    `json:"name"`
	PublicRepositoriesCount int64     `json:"public_repositories_count"`
	Title                   string    `json:"title"`
	TwitterUsername         string    `json:"twitter_username"`
	UpdatedAt               time.Time `json:"updated_at"`
	URL                     string    `json:"url"`
}

func (m MemberSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MemberSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"avatar_url", "bio", "company", "created_at", "email", "followers_count", "following_count", "location", "login", "name", "public_repositories_count", "title", "twitter_username", "updated_at", "url"}); err != nil {
		return err
	}
	return nil
}

func (o *MemberSchema) GetAvatarURL() string {
	if o == nil {
		return ""
	}
	return o.AvatarURL
}

func (o *MemberSchema) GetBio() string {
	if o == nil {
		return ""
	}
	return o.Bio
}

func (o *MemberSchema) GetCompany() string {
	if o == nil {
		return ""
	}
	return o.Company
}

func (o *MemberSchema) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *MemberSchema) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *MemberSchema) GetFollowersCount() int64 {
	if o == nil {
		return 0
	}
	return o.FollowersCount
}

func (o *MemberSchema) GetFollowingCount() int64 {
	if o == nil {
		return 0
	}
	return o.FollowingCount
}

func (o *MemberSchema) GetLocation() string {
	if o == nil {
		return ""
	}
	return o.Location
}

func (o *MemberSchema) GetLogin() string {
	if o == nil {
		return ""
	}
	return o.Login
}

func (o *MemberSchema) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *MemberSchema) GetPublicRepositoriesCount() int64 {
	if o == nil {
		return 0
	}
	return o.PublicRepositoriesCount
}

func (o *MemberSchema) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *MemberSchema) GetTwitterUsername() string {
	if o == nil {
		return ""
	}
	return o.TwitterUsername
}

func (o *MemberSchema) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *MemberSchema) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
