// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Member - Schema for Member (minimal fields for list display).
type Member struct {
	AvatarURL string    `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	Login     string    `json:"login"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	URL       string    `json:"url"`
}

func (m Member) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Member) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Member) GetAvatarURL() string {
	if m == nil {
		return ""
	}
	return m.AvatarURL
}

func (m *Member) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *Member) GetLogin() string {
	if m == nil {
		return ""
	}
	return m.Login
}

func (m *Member) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Member) GetUpdatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.UpdatedAt
}

func (m *Member) GetURL() string {
	if m == nil {
		return ""
	}
	return m.URL
}
