// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Milestone - Schema for Milestone (minimal fields for list display).
type Milestone struct {
	CreatedAt time.Time `json:"created_at"`
	Number    int64     `json:"number"`
	State     State     `json:"state"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	URL       string    `json:"url"`
}

func (m Milestone) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Milestone) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"created_at", "number", "state", "title", "updated_at", "url"}); err != nil {
		return err
	}
	return nil
}

func (m *Milestone) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *Milestone) GetNumber() int64 {
	if m == nil {
		return 0
	}
	return m.Number
}

func (m *Milestone) GetState() State {
	if m == nil {
		return State("")
	}
	return m.State
}

func (m *Milestone) GetTitle() string {
	if m == nil {
		return ""
	}
	return m.Title
}

func (m *Milestone) GetUpdatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.UpdatedAt
}

func (m *Milestone) GetURL() string {
	if m == nil {
		return ""
	}
	return m.URL
}
