// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// MilestoneDetail - Detail schema for Milestone (used in single item endpoints).
type MilestoneDetail struct {
	CreatedAt         time.Time  `json:"created_at"`
	Number            int64      `json:"number"`
	State             State      `json:"state"`
	Title             string     `json:"title"`
	UpdatedAt         time.Time  `json:"updated_at"`
	URL               string     `json:"url"`
	Body              string     `json:"body"`
	ClosedIssuesCount int64      `json:"closed_issues_count"`
	DueOn             *time.Time `json:"due_on"`
	OpenIssuesCount   int64      `json:"open_issues_count"`
}

func (m MilestoneDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MilestoneDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"created_at", "number", "state", "title", "updated_at", "url", "body", "closed_issues_count", "open_issues_count"}); err != nil {
		return err
	}
	return nil
}

func (m *MilestoneDetail) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *MilestoneDetail) GetNumber() int64 {
	if m == nil {
		return 0
	}
	return m.Number
}

func (m *MilestoneDetail) GetState() State {
	if m == nil {
		return State("")
	}
	return m.State
}

func (m *MilestoneDetail) GetTitle() string {
	if m == nil {
		return ""
	}
	return m.Title
}

func (m *MilestoneDetail) GetUpdatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.UpdatedAt
}

func (m *MilestoneDetail) GetURL() string {
	if m == nil {
		return ""
	}
	return m.URL
}

func (m *MilestoneDetail) GetBody() string {
	if m == nil {
		return ""
	}
	return m.Body
}

func (m *MilestoneDetail) GetClosedIssuesCount() int64 {
	if m == nil {
		return 0
	}
	return m.ClosedIssuesCount
}

func (m *MilestoneDetail) GetDueOn() *time.Time {
	if m == nil {
		return nil
	}
	return m.DueOn
}

func (m *MilestoneDetail) GetOpenIssuesCount() int64 {
	if m == nil {
		return 0
	}
	return m.OpenIssuesCount
}
