// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// OrganizationDetail - Detail schema for Organization (used in single item endpoints).
type OrganizationDetail struct {
	CreatedAt time.Time `json:"created_at"`
	Login     string    `json:"login"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	Company   string    `json:"company"`
	Location  string    `json:"location"`
}

func (o OrganizationDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationDetail) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OrganizationDetail) GetLogin() string {
	if o == nil {
		return ""
	}
	return o.Login
}

func (o *OrganizationDetail) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationDetail) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *OrganizationDetail) GetCompany() string {
	if o == nil {
		return ""
	}
	return o.Company
}

func (o *OrganizationDetail) GetLocation() string {
	if o == nil {
		return ""
	}
	return o.Location
}
