// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// OrganizationSchema - Schema for Organization.
type OrganizationSchema struct {
	Company   string    `json:"company"`
	CreatedAt time.Time `json:"created_at"`
	Location  string    `json:"location"`
	Login     string    `json:"login"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (o OrganizationSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, []string{"company", "created_at", "location", "login", "name", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationSchema) GetCompany() string {
	if o == nil {
		return ""
	}
	return o.Company
}

func (o *OrganizationSchema) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OrganizationSchema) GetLocation() string {
	if o == nil {
		return ""
	}
	return o.Location
}

func (o *OrganizationSchema) GetLogin() string {
	if o == nil {
		return ""
	}
	return o.Login
}

func (o *OrganizationSchema) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationSchema) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
