// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedMilestone struct {
	// Current page number
	CurrentPage int64 `json:"current_page"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool        `json:"has_previous"`
	Items       []Milestone `json:"items"`
	// Total number of items
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}

func (p *PagedMilestone) GetCurrentPage() int64 {
	if p == nil {
		return 0
	}
	return p.CurrentPage
}

func (p *PagedMilestone) GetHasNext() bool {
	if p == nil {
		return false
	}
	return p.HasNext
}

func (p *PagedMilestone) GetHasPrevious() bool {
	if p == nil {
		return false
	}
	return p.HasPrevious
}

func (p *PagedMilestone) GetItems() []Milestone {
	if p == nil {
		return []Milestone{}
	}
	return p.Items
}

func (p *PagedMilestone) GetTotalCount() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PagedMilestone) GetTotalPages() int64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}
