// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedMemberSchema struct {
	Items []MemberSchema `json:"items"`
	Count int64          `json:"count"`
}

func (o *PagedMemberSchema) GetItems() []MemberSchema {
	if o == nil {
		return []MemberSchema{}
	}
	return o.Items
}

func (o *PagedMemberSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
