// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedOrganization struct {
	// Current page number
	CurrentPage int64 `json:"current_page"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool           `json:"has_previous"`
	Items       []Organization `json:"items"`
	// Total number of items
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}

func (p *PagedOrganization) GetCurrentPage() int64 {
	if p == nil {
		return 0
	}
	return p.CurrentPage
}

func (p *PagedOrganization) GetHasNext() bool {
	if p == nil {
		return false
	}
	return p.HasNext
}

func (p *PagedOrganization) GetHasPrevious() bool {
	if p == nil {
		return false
	}
	return p.HasPrevious
}

func (p *PagedOrganization) GetItems() []Organization {
	if p == nil {
		return []Organization{}
	}
	return p.Items
}

func (p *PagedOrganization) GetTotalCount() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PagedOrganization) GetTotalPages() int64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}
