// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedCommittee struct {
	// Current page number
	CurrentPage int64 `json:"current_page"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool        `json:"has_previous"`
	Items       []Committee `json:"items"`
	// Total number of items
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}

func (p *PagedCommittee) GetCurrentPage() int64 {
	if p == nil {
		return 0
	}
	return p.CurrentPage
}

func (p *PagedCommittee) GetHasNext() bool {
	if p == nil {
		return false
	}
	return p.HasNext
}

func (p *PagedCommittee) GetHasPrevious() bool {
	if p == nil {
		return false
	}
	return p.HasPrevious
}

func (p *PagedCommittee) GetItems() []Committee {
	if p == nil {
		return []Committee{}
	}
	return p.Items
}

func (p *PagedCommittee) GetTotalCount() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PagedCommittee) GetTotalPages() int64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}
