// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedMemberSchema struct {
	Items []MemberSchema `json:"items"`
	Count int64          `json:"count"`
}

func (p *PagedMemberSchema) GetItems() []MemberSchema {
	if p == nil {
		return []MemberSchema{}
	}
	return p.Items
}

func (p *PagedMemberSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
