// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedRepository struct {
	// Current page number
	CurrentPage int64 `json:"current_page"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool         `json:"has_previous"`
	Items       []Repository `json:"items"`
	// Total number of items
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}

func (p *PagedRepository) GetCurrentPage() int64 {
	if p == nil {
		return 0
	}
	return p.CurrentPage
}

func (p *PagedRepository) GetHasNext() bool {
	if p == nil {
		return false
	}
	return p.HasNext
}

func (p *PagedRepository) GetHasPrevious() bool {
	if p == nil {
		return false
	}
	return p.HasPrevious
}

func (p *PagedRepository) GetItems() []Repository {
	if p == nil {
		return []Repository{}
	}
	return p.Items
}

func (p *PagedRepository) GetTotalCount() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PagedRepository) GetTotalPages() int64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}
