// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedRepositorySchema struct {
	Items []RepositorySchema `json:"items"`
	Count int64              `json:"count"`
}

func (o *PagedRepositorySchema) GetItems() []RepositorySchema {
	if o == nil {
		return []RepositorySchema{}
	}
	return o.Items
}

func (o *PagedRepositorySchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
