// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedProjectSchema struct {
	Items []ProjectSchema `json:"items"`
	Count int64           `json:"count"`
}

func (o *PagedProjectSchema) GetItems() []ProjectSchema {
	if o == nil {
		return []ProjectSchema{}
	}
	return o.Items
}

func (o *PagedProjectSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
