// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedReleaseSchema struct {
	Items []ReleaseSchema `json:"items"`
	Count int64           `json:"count"`
}

func (p *PagedReleaseSchema) GetItems() []ReleaseSchema {
	if p == nil {
		return []ReleaseSchema{}
	}
	return p.Items
}

func (p *PagedReleaseSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
