// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedCommitteeSchema struct {
	Items []CommitteeSchema `json:"items"`
	Count int64             `json:"count"`
}

func (o *PagedCommitteeSchema) GetItems() []CommitteeSchema {
	if o == nil {
		return []CommitteeSchema{}
	}
	return o.Items
}

func (o *PagedCommitteeSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
