// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedSponsorSchema struct {
	Items []SponsorSchema `json:"items"`
	Count int64           `json:"count"`
}

func (p *PagedSponsorSchema) GetItems() []SponsorSchema {
	if p == nil {
		return []SponsorSchema{}
	}
	return p.Items
}

func (p *PagedSponsorSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
