// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedOrganizationSchema struct {
	Items []OrganizationSchema `json:"items"`
	Count int64                `json:"count"`
}

func (p *PagedOrganizationSchema) GetItems() []OrganizationSchema {
	if p == nil {
		return []OrganizationSchema{}
	}
	return p.Items
}

func (p *PagedOrganizationSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
