// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedIssueSchema struct {
	Items []IssueSchema `json:"items"`
	Count int64         `json:"count"`
}

func (p *PagedIssueSchema) GetItems() []IssueSchema {
	if p == nil {
		return []IssueSchema{}
	}
	return p.Items
}

func (p *PagedIssueSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
