// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedCommitteeSchema struct {
	Items []CommitteeSchema `json:"items"`
	Count int64             `json:"count"`
}

func (p *PagedCommitteeSchema) GetItems() []CommitteeSchema {
	if p == nil {
		return []CommitteeSchema{}
	}
	return p.Items
}

func (p *PagedCommitteeSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
