// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedEvent struct {
	// Current page number
	CurrentPage int64 `json:"current_page"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool    `json:"has_previous"`
	Items       []Event `json:"items"`
	// Total number of items
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}

func (p *PagedEvent) GetCurrentPage() int64 {
	if p == nil {
		return 0
	}
	return p.CurrentPage
}

func (p *PagedEvent) GetHasNext() bool {
	if p == nil {
		return false
	}
	return p.HasNext
}

func (p *PagedEvent) GetHasPrevious() bool {
	if p == nil {
		return false
	}
	return p.HasPrevious
}

func (p *PagedEvent) GetItems() []Event {
	if p == nil {
		return []Event{}
	}
	return p.Items
}

func (p *PagedEvent) GetTotalCount() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PagedEvent) GetTotalPages() int64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}
