// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedChapterSchema struct {
	Items []ChapterSchema `json:"items"`
	Count int64           `json:"count"`
}

func (p *PagedChapterSchema) GetItems() []ChapterSchema {
	if p == nil {
		return []ChapterSchema{}
	}
	return p.Items
}

func (p *PagedChapterSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
