// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedChapterSchema struct {
	Items []ChapterSchema `json:"items"`
	Count int64           `json:"count"`
}

func (o *PagedChapterSchema) GetItems() []ChapterSchema {
	if o == nil {
		return []ChapterSchema{}
	}
	return o.Items
}

func (o *PagedChapterSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
