// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedEventSchema struct {
	Items []EventSchema `json:"items"`
	Count int64         `json:"count"`
}

func (o *PagedEventSchema) GetItems() []EventSchema {
	if o == nil {
		return []EventSchema{}
	}
	return o.Items
}

func (o *PagedEventSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
