// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedProjectSchema struct {
	Items []ProjectSchema `json:"items"`
	Count int64           `json:"count"`
}

func (p *PagedProjectSchema) GetItems() []ProjectSchema {
	if p == nil {
		return []ProjectSchema{}
	}
	return p.Items
}

func (p *PagedProjectSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
