// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedEventSchema struct {
	Items []EventSchema `json:"items"`
	Count int64         `json:"count"`
}

func (p *PagedEventSchema) GetItems() []EventSchema {
	if p == nil {
		return []EventSchema{}
	}
	return p.Items
}

func (p *PagedEventSchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
