// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedRepositorySchema struct {
	Items []RepositorySchema `json:"items"`
	Count int64              `json:"count"`
}

func (p *PagedRepositorySchema) GetItems() []RepositorySchema {
	if p == nil {
		return []RepositorySchema{}
	}
	return p.Items
}

func (p *PagedRepositorySchema) GetCount() int64 {
	if p == nil {
		return 0
	}
	return p.Count
}
