// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedRelease struct {
	// Current page number
	CurrentPage int64 `json:"current_page"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool      `json:"has_previous"`
	Items       []Release `json:"items"`
	// Total number of items
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}

func (p *PagedRelease) GetCurrentPage() int64 {
	if p == nil {
		return 0
	}
	return p.CurrentPage
}

func (p *PagedRelease) GetHasNext() bool {
	if p == nil {
		return false
	}
	return p.HasNext
}

func (p *PagedRelease) GetHasPrevious() bool {
	if p == nil {
		return false
	}
	return p.HasPrevious
}

func (p *PagedRelease) GetItems() []Release {
	if p == nil {
		return []Release{}
	}
	return p.Items
}

func (p *PagedRelease) GetTotalCount() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PagedRelease) GetTotalPages() int64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}
