// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedReleaseSchema struct {
	Items []ReleaseSchema `json:"items"`
	Count int64           `json:"count"`
}

func (o *PagedReleaseSchema) GetItems() []ReleaseSchema {
	if o == nil {
		return []ReleaseSchema{}
	}
	return o.Items
}

func (o *PagedReleaseSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
