// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedSnapshotIssue struct {
	// Current page number
	CurrentPage int64 `json:"current_page"`
	// Whether there is a next page
	HasNext bool `json:"has_next"`
	// Whether there is a previous page
	HasPrevious bool            `json:"has_previous"`
	Items       []SnapshotIssue `json:"items"`
	// Total number of items
	TotalCount int64 `json:"total_count"`
	// Total number of pages
	TotalPages int64 `json:"total_pages"`
}

func (p *PagedSnapshotIssue) GetCurrentPage() int64 {
	if p == nil {
		return 0
	}
	return p.CurrentPage
}

func (p *PagedSnapshotIssue) GetHasNext() bool {
	if p == nil {
		return false
	}
	return p.HasNext
}

func (p *PagedSnapshotIssue) GetHasPrevious() bool {
	if p == nil {
		return false
	}
	return p.HasPrevious
}

func (p *PagedSnapshotIssue) GetItems() []SnapshotIssue {
	if p == nil {
		return []SnapshotIssue{}
	}
	return p.Items
}

func (p *PagedSnapshotIssue) GetTotalCount() int64 {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PagedSnapshotIssue) GetTotalPages() int64 {
	if p == nil {
		return 0
	}
	return p.TotalPages
}
