// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedOrganizationSchema struct {
	Items []OrganizationSchema `json:"items"`
	Count int64                `json:"count"`
}

func (o *PagedOrganizationSchema) GetItems() []OrganizationSchema {
	if o == nil {
		return []OrganizationSchema{}
	}
	return o.Items
}

func (o *PagedOrganizationSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
