// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PagedIssueSchema struct {
	Items []IssueSchema `json:"items"`
	Count int64         `json:"count"`
}

func (o *PagedIssueSchema) GetItems() []IssueSchema {
	if o == nil {
		return []IssueSchema{}
	}
	return o.Items
}

func (o *PagedIssueSchema) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}
