// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ProjectLevel - Enum for OWASP project levels.
type ProjectLevel string

const (
	ProjectLevelOther      ProjectLevel = "other"
	ProjectLevelIncubator  ProjectLevel = "incubator"
	ProjectLevelLab        ProjectLevel = "lab"
	ProjectLevelProduction ProjectLevel = "production"
	ProjectLevelFlagship   ProjectLevel = "flagship"
)

func (e ProjectLevel) ToPointer() *ProjectLevel {
	return &e
}
func (e *ProjectLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "other":
		fallthrough
	case "incubator":
		fallthrough
	case "lab":
		fallthrough
	case "production":
		fallthrough
	case "flagship":
		*e = ProjectLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProjectLevel: %v", v)
	}
}
