// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// ProjectDetail - Detail schema for Project (used in single item endpoints).
type ProjectDetail struct {
	CreatedAt time.Time `json:"created_at"`
	Key       string    `json:"key"`
	// Enum for OWASP project levels.
	Level       ProjectLevel `json:"level"`
	Name        string       `json:"name"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Description string       `json:"description"`
}

func (p ProjectDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProjectDetail) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *ProjectDetail) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *ProjectDetail) GetLevel() ProjectLevel {
	if p == nil {
		return ProjectLevel("")
	}
	return p.Level
}

func (p *ProjectDetail) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *ProjectDetail) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *ProjectDetail) GetDescription() string {
	if p == nil {
		return ""
	}
	return p.Description
}
