// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// ProjectSchema - Schema for Project.
type ProjectSchema struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	// Enum for OWASP project levels.
	Level     ProjectLevel `json:"level"`
	Name      string       `json:"name"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (p ProjectSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"created_at", "description", "level", "name", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (o *ProjectSchema) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ProjectSchema) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *ProjectSchema) GetLevel() ProjectLevel {
	if o == nil {
		return ProjectLevel("")
	}
	return o.Level
}

func (o *ProjectSchema) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ProjectSchema) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
