// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Project - Schema for Project (minimal fields for list display).
type Project struct {
	CreatedAt time.Time `json:"created_at"`
	Key       string    `json:"key"`
	// Enum for OWASP project levels.
	Level     ProjectLevel `json:"level"`
	Name      string       `json:"name"`
	UpdatedAt time.Time    `json:"updated_at"`
}

func (p Project) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Project) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Project) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Project) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *Project) GetLevel() ProjectLevel {
	if p == nil {
		return ProjectLevel("")
	}
	return p.Level
}

func (p *Project) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Project) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}
