// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ProjectType - Enum for OWASP project types.
type ProjectType string

const (
	ProjectTypeCode          ProjectType = "code"
	ProjectTypeDocumentation ProjectType = "documentation"
	ProjectTypeOther         ProjectType = "other"
	ProjectTypeTool          ProjectType = "tool"
)

func (e ProjectType) ToPointer() *ProjectType {
	return &e
}
func (e *ProjectType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "code":
		fallthrough
	case "documentation":
		fallthrough
	case "other":
		fallthrough
	case "tool":
		*e = ProjectType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProjectType: %v", v)
	}
}
