// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// ReleaseDetail - Detail schema for Release (used in single item endpoints).
type ReleaseDetail struct {
	CreatedAt   time.Time  `json:"created_at"`
	Name        string     `json:"name"`
	PublishedAt *time.Time `json:"published_at,omitempty"`
	TagName     string     `json:"tag_name"`
	Description string     `json:"description"`
}

func (r ReleaseDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReleaseDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReleaseDetail) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *ReleaseDetail) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ReleaseDetail) GetPublishedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.PublishedAt
}

func (r *ReleaseDetail) GetTagName() string {
	if r == nil {
		return ""
	}
	return r.TagName
}

func (r *ReleaseDetail) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}
