// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Release - Schema for Release (minimal fields for list display).
type Release struct {
	CreatedAt   time.Time  `json:"created_at"`
	Name        string     `json:"name"`
	PublishedAt *time.Time `json:"published_at,omitempty"`
	TagName     string     `json:"tag_name"`
}

func (r Release) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Release) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Release) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *Release) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *Release) GetPublishedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.PublishedAt
}

func (r *Release) GetTagName() string {
	if r == nil {
		return ""
	}
	return r.TagName
}
