// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// ReleaseSchema - Schema for Release.
type ReleaseSchema struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Name        string    `json:"name"`
	PublishedAt time.Time `json:"published_at"`
	TagName     string    `json:"tag_name"`
}

func (r ReleaseSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReleaseSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"created_at", "description", "name", "published_at", "tag_name"}); err != nil {
		return err
	}
	return nil
}

func (r *ReleaseSchema) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *ReleaseSchema) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *ReleaseSchema) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ReleaseSchema) GetPublishedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.PublishedAt
}

func (r *ReleaseSchema) GetTagName() string {
	if r == nil {
		return ""
	}
	return r.TagName
}
