// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// RepositoryDetail - Detail schema for Repository (used in single item endpoints).
type RepositoryDetail struct {
	CreatedAt   time.Time `json:"created_at"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
	Description *string   `json:"description,omitempty"`
}

func (r RepositoryDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RepositoryDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"created_at", "name", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (r *RepositoryDetail) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *RepositoryDetail) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RepositoryDetail) GetUpdatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.UpdatedAt
}

func (r *RepositoryDetail) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}
