// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// RepositoryDetail - Detail schema for Repository (used in single item endpoints).
type RepositoryDetail struct {
	CreatedAt         time.Time `json:"created_at"`
	Name              string    `json:"name"`
	UpdatedAt         time.Time `json:"updated_at"`
	CommitsCount      int64     `json:"commits_count"`
	ContributorsCount int64     `json:"contributors_count"`
	Description       *string   `json:"description,omitempty"`
	ForksCount        int64     `json:"forks_count"`
	OpenIssuesCount   int64     `json:"open_issues_count"`
	StarsCount        int64     `json:"stars_count"`
}

func (r RepositoryDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RepositoryDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"created_at", "name", "updated_at", "commits_count", "contributors_count", "forks_count", "open_issues_count", "stars_count"}); err != nil {
		return err
	}
	return nil
}

func (r *RepositoryDetail) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *RepositoryDetail) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RepositoryDetail) GetUpdatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.UpdatedAt
}

func (r *RepositoryDetail) GetCommitsCount() int64 {
	if r == nil {
		return 0
	}
	return r.CommitsCount
}

func (r *RepositoryDetail) GetContributorsCount() int64 {
	if r == nil {
		return 0
	}
	return r.ContributorsCount
}

func (r *RepositoryDetail) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RepositoryDetail) GetForksCount() int64 {
	if r == nil {
		return 0
	}
	return r.ForksCount
}

func (r *RepositoryDetail) GetOpenIssuesCount() int64 {
	if r == nil {
		return 0
	}
	return r.OpenIssuesCount
}

func (r *RepositoryDetail) GetStarsCount() int64 {
	if r == nil {
		return 0
	}
	return r.StarsCount
}
