// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	APIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key,env=nest_api_key"`
}

func (s *Security) GetAPIKey() *string {
	if s == nil {
		return nil
	}
	return s.APIKey
}
