// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	APIKeyHeader *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key,env=nest_api_key_header"`
}

func (o *Security) GetAPIKeyHeader() *string {
	if o == nil {
		return nil
	}
	return o.APIKeyHeader
}
