// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// Snapshot - Schema for Snapshot (minimal fields for list display).
type Snapshot struct {
	CreatedAt time.Time `json:"created_at"`
	EndAt     time.Time `json:"end_at"`
	Key       string    `json:"key"`
	StartAt   time.Time `json:"start_at"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (s Snapshot) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Snapshot) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Snapshot) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Snapshot) GetEndAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.EndAt
}

func (s *Snapshot) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *Snapshot) GetStartAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.StartAt
}

func (s *Snapshot) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *Snapshot) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
