// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// SnapshotDetail - Detail schema for Snapshot (used in single item endpoints).
type SnapshotDetail struct {
	CreatedAt        time.Time `json:"created_at"`
	EndAt            time.Time `json:"end_at"`
	Key              string    `json:"key"`
	StartAt          time.Time `json:"start_at"`
	Title            string    `json:"title"`
	UpdatedAt        time.Time `json:"updated_at"`
	NewChaptersCount int64     `json:"new_chapters_count"`
	NewIssuesCount   int64     `json:"new_issues_count"`
	NewProjectsCount int64     `json:"new_projects_count"`
	NewReleasesCount int64     `json:"new_releases_count"`
	NewUsersCount    int64     `json:"new_users_count"`
}

func (s SnapshotDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SnapshotDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SnapshotDetail) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SnapshotDetail) GetEndAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.EndAt
}

func (s *SnapshotDetail) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *SnapshotDetail) GetStartAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.StartAt
}

func (s *SnapshotDetail) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *SnapshotDetail) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}

func (s *SnapshotDetail) GetNewChaptersCount() int64 {
	if s == nil {
		return 0
	}
	return s.NewChaptersCount
}

func (s *SnapshotDetail) GetNewIssuesCount() int64 {
	if s == nil {
		return 0
	}
	return s.NewIssuesCount
}

func (s *SnapshotDetail) GetNewProjectsCount() int64 {
	if s == nil {
		return 0
	}
	return s.NewProjectsCount
}

func (s *SnapshotDetail) GetNewReleasesCount() int64 {
	if s == nil {
		return 0
	}
	return s.NewReleasesCount
}

func (s *SnapshotDetail) GetNewUsersCount() int64 {
	if s == nil {
		return 0
	}
	return s.NewUsersCount
}
