// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// SnapshotRelease - Schema for Snapshot Release (used in list endpoints).
type SnapshotRelease struct {
	CreatedAt         time.Time  `json:"created_at"`
	Name              string     `json:"name"`
	PublishedAt       *time.Time `json:"published_at,omitempty"`
	TagName           string     `json:"tag_name"`
	OrganizationLogin *string    `json:"organization_login"`
	RepositoryName    *string    `json:"repository_name"`
}

func (s SnapshotRelease) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SnapshotRelease) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SnapshotRelease) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SnapshotRelease) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SnapshotRelease) GetPublishedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.PublishedAt
}

func (s *SnapshotRelease) GetTagName() string {
	if s == nil {
		return ""
	}
	return s.TagName
}

func (s *SnapshotRelease) GetOrganizationLogin() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationLogin
}

func (s *SnapshotRelease) GetRepositoryName() *string {
	if s == nil {
		return nil
	}
	return s.RepositoryName
}
