// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/owasp/nest-sdk/internal/utils"
	"time"
)

// SnapshotIssue - Schema for Snapshot Issue (used in list endpoints).
type SnapshotIssue struct {
	CreatedAt         time.Time `json:"created_at"`
	State             State     `json:"state"`
	Title             string    `json:"title"`
	UpdatedAt         time.Time `json:"updated_at"`
	URL               string    `json:"url"`
	OrganizationLogin *string   `json:"organization_login"`
	RepositoryName    *string   `json:"repository_name"`
}

func (s SnapshotIssue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SnapshotIssue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SnapshotIssue) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SnapshotIssue) GetState() State {
	if s == nil {
		return State("")
	}
	return s.State
}

func (s *SnapshotIssue) GetTitle() string {
	if s == nil {
		return ""
	}
	return s.Title
}

func (s *SnapshotIssue) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}

func (s *SnapshotIssue) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *SnapshotIssue) GetOrganizationLogin() *string {
	if s == nil {
		return nil
	}
	return s.OrganizationLogin
}

func (s *SnapshotIssue) GetRepositoryName() *string {
	if s == nil {
		return nil
	}
	return s.RepositoryName
}
