// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SponsorDetail - Detail schema for Sponsor (used in single item endpoints).
type SponsorDetail struct {
	ImageURL    string `json:"image_url"`
	Key         string `json:"key"`
	Name        string `json:"name"`
	SponsorType string `json:"sponsor_type"`
	URL         string `json:"url"`
	Description string `json:"description"`
	IsMember    bool   `json:"is_member"`
	JobURL      string `json:"job_url"`
	MemberType  string `json:"member_type"`
}

func (s *SponsorDetail) GetImageURL() string {
	if s == nil {
		return ""
	}
	return s.ImageURL
}

func (s *SponsorDetail) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *SponsorDetail) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SponsorDetail) GetSponsorType() string {
	if s == nil {
		return ""
	}
	return s.SponsorType
}

func (s *SponsorDetail) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *SponsorDetail) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *SponsorDetail) GetIsMember() bool {
	if s == nil {
		return false
	}
	return s.IsMember
}

func (s *SponsorDetail) GetJobURL() string {
	if s == nil {
		return ""
	}
	return s.JobURL
}

func (s *SponsorDetail) GetMemberType() string {
	if s == nil {
		return ""
	}
	return s.MemberType
}
