// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SponsorSchema - Schema for Sponsor.
type SponsorSchema struct {
	Description string `json:"description"`
	ImageURL    string `json:"image_url"`
	IsMember    bool   `json:"is_member"`
	JobURL      string `json:"job_url"`
	Key         string `json:"key"`
	MemberType  string `json:"member_type"`
	Name        string `json:"name"`
	SponsorType string `json:"sponsor_type"`
	URL         string `json:"url"`
}

func (s *SponsorSchema) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *SponsorSchema) GetImageURL() string {
	if s == nil {
		return ""
	}
	return s.ImageURL
}

func (s *SponsorSchema) GetIsMember() bool {
	if s == nil {
		return false
	}
	return s.IsMember
}

func (s *SponsorSchema) GetJobURL() string {
	if s == nil {
		return ""
	}
	return s.JobURL
}

func (s *SponsorSchema) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *SponsorSchema) GetMemberType() string {
	if s == nil {
		return ""
	}
	return s.MemberType
}

func (s *SponsorSchema) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SponsorSchema) GetSponsorType() string {
	if s == nil {
		return ""
	}
	return s.SponsorType
}

func (s *SponsorSchema) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}
