// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Sponsor - Schema for Sponsor (minimal fields for list display).
type Sponsor struct {
	ImageURL    string `json:"image_url"`
	Key         string `json:"key"`
	Name        string `json:"name"`
	SponsorType string `json:"sponsor_type"`
	URL         string `json:"url"`
}

func (s *Sponsor) GetImageURL() string {
	if s == nil {
		return ""
	}
	return s.ImageURL
}

func (s *Sponsor) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *Sponsor) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Sponsor) GetSponsorType() string {
	if s == nil {
		return ""
	}
	return s.SponsorType
}

func (s *Sponsor) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}
