// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/owasp/nest-sdk/internal/utils"
)

type ErrorsType string

const (
	ErrorsTypeArrayOfMapOfAny ErrorsType = "arrayOfMapOfAny"
	ErrorsTypeMapOfAny        ErrorsType = "mapOfAny"
)

type Errors struct {
	ArrayOfMapOfAny []map[string]any `queryParam:"inline" union:"member"`
	MapOfAny        map[string]any   `queryParam:"inline" union:"member"`

	Type ErrorsType
}

func CreateErrorsArrayOfMapOfAny(arrayOfMapOfAny []map[string]any) Errors {
	typ := ErrorsTypeArrayOfMapOfAny

	return Errors{
		ArrayOfMapOfAny: arrayOfMapOfAny,
		Type:            typ,
	}
}

func CreateErrorsMapOfAny(mapOfAny map[string]any) Errors {
	typ := ErrorsTypeMapOfAny

	return Errors{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func (u *Errors) UnmarshalJSON(data []byte) error {

	var arrayOfMapOfAny []map[string]any = []map[string]any{}
	if err := utils.UnmarshalJSON(data, &arrayOfMapOfAny, "", true, nil); err == nil {
		u.ArrayOfMapOfAny = arrayOfMapOfAny
		u.Type = ErrorsTypeArrayOfMapOfAny
		return nil
	}

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = ErrorsTypeMapOfAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Errors", string(data))
}

func (u Errors) MarshalJSON() ([]byte, error) {
	if u.ArrayOfMapOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfMapOfAny, "", true)
	}

	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type Errors: all fields are null")
}
