// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// ChapterErrorResponse - Chapter error response schema.
type ChapterErrorResponse struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ChapterErrorResponse{}

func (e *ChapterErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
