// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// ChapterError - Chapter error schema.
type ChapterError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ChapterError{}

func (e *ChapterError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
