// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// CommitteeError - Committee error schema.
type CommitteeError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CommitteeError{}

func (e *CommitteeError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
