// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// EventError - Event error schema.
type EventError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &EventError{}

func (e *EventError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
