// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// IssueError - Issue error schema.
type IssueError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &IssueError{}

func (e *IssueError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
