// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// MemberError - Member error schema.
type MemberError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &MemberError{}

func (e *MemberError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
