// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// MilestoneError - Milestone error schema.
type MilestoneError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &MilestoneError{}

func (e *MilestoneError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
