// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// OrganizationError - Organization error schema.
type OrganizationError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &OrganizationError{}

func (e *OrganizationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
