// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// OrganizationErrorResponse - Organization error response schema.
type OrganizationErrorResponse struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &OrganizationErrorResponse{}

func (e *OrganizationErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
