// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// ProjectErrorResponse - Project error response schema.
type ProjectErrorResponse struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ProjectErrorResponse{}

func (e *ProjectErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
