// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// ProjectError - Project error schema.
type ProjectError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ProjectError{}

func (e *ProjectError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
