// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// ReleaseError - Release error schema.
type ReleaseError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ReleaseError{}

func (e *ReleaseError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
