// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// RepositoryError - Repository error schema.
type RepositoryError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &RepositoryError{}

func (e *RepositoryError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
