// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// SnapshotError - Snapshot error schema.
type SnapshotError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &SnapshotError{}

func (e *SnapshotError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
