// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// SponsorError - Sponsor error schema.
type SponsorError struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &SponsorError{}

func (e *SponsorError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
