// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// SponsorErrorResponse - Sponsor error response schema.
type SponsorErrorResponse struct {
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &SponsorErrorResponse{}

func (e *SponsorErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
