// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/owasp/nest-sdk/models/components"
)

// ValidationErrorSchema - Schema for validation error.
type ValidationErrorSchema struct {
	Message  string                  `json:"message"`
	Errors   *components.Errors      `json:"errors,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ValidationErrorSchema{}

func (e *ValidationErrorSchema) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
